import type { IconMap } from '~/theme/_shared/icon-registry';

export default <IconMap>{
    // Shell & Navigation — carbon icons for clean techy feel
    'shell.sidebar.toggle.left': 'carbon:side-panel-close',
    'shell.sidebar.toggle.right': 'carbon:side-panel-open',
    'shell.pane.add': 'carbon:add',
    'shell.pane.close': 'carbon:close',
    'shell.theme.light': 'carbon:light',
    'shell.theme.dark': 'carbon:asleep',
    'shell.menu': 'carbon:overflow-menu-vertical',
    'shell.back': 'carbon:arrow-left',
    'shell.expand': 'carbon:folder',
    'shell.collapse': 'carbon:folder',

    // Chat Interface
    'chat.send': 'carbon:send-alt',
    'chat.stop': 'carbon:stop-filled',
    'chat.attach': 'carbon:add',
    'chat.upload': 'carbon:cloud-upload',
    'chat.clear': 'carbon:close',
    'chat.model.search': 'carbon:search',
    'chat.model.settings': 'carbon:settings-adjust',
    'chat.model.catalog': 'carbon:bot',
    'chat.system_prompt': 'carbon:script',
    'chat.message.continue': 'carbon:continue',

    // Chat Messages
    'chat.message.copy': 'carbon:copy',
    'chat.message.retry': 'carbon:renew',
    'chat.message.edit': 'carbon:edit',
    'chat.message.branch': 'carbon:branch',
    'chat.message.delete': 'carbon:trash-can',
    'chat.reasoning': 'carbon:idea',

    // Tool Indicators
    'chat.tool.loader': 'carbon:renew',
    'chat.tool.check': 'carbon:checkmark',
    'chat.tool.error': 'carbon:close',
    'chat.tool.wrench': 'carbon:tool-kit',

    // Sidebar
    'sidebar.search': 'carbon:search',
    'sidebar.new_chat': 'carbon:chat',
    'sidebar.new_folder': 'carbon:folder-add',
    'sidebar.new_note': 'carbon:document-add',
    'sidebar.edit': 'carbon:edit',
    'sidebar.delete': 'carbon:trash-can',
    'sidebar.folder': 'carbon:folder',
    'sidebar.chat': 'carbon:chat',
    'sidebar.note': 'carbon:document',
    'sidebar.settings': 'carbon:settings-adjust',
    'sidebar.user': 'carbon:user',
    'sidebar.activity': 'carbon:activity',
    'sidebar.credits': 'carbon:finance',
    'sidebar.project.root': 'carbon:home',
    'sidebar.page.home': 'carbon:home',
    'sidebar.page.messages': 'carbon:chat',
    'sidebar.page.default': 'carbon:grid',

    // Common UI
    'ui.check': 'carbon:checkmark',
    'ui.close': 'carbon:close',
    'ui.copy': 'carbon:copy',
    'ui.trash': 'carbon:trash-can',
    'ui.edit': 'carbon:edit',
    'ui.warning': 'carbon:warning-alt',
    'ui.info': 'carbon:information',
    'ui.loading': 'carbon:renew',
    'ui.more': 'carbon:overflow-menu-vertical',
    'ui.download': 'carbon:download',
    'ui.upload': 'carbon:cloud-upload',
    'ui.search': 'carbon:search',
    'ui.filter': 'carbon:filter',
    'ui.sort': 'carbon:sort-ascending',
    'ui.view': 'carbon:view',
    'ui.view_off': 'carbon:view-off',
    'ui.lock': 'carbon:locked',
    'ui.unlock': 'carbon:unlocked',
    'ui.settings': 'carbon:settings-adjust',
    'ui.unknown': 'carbon:warning-alt',
    'ui.clock': 'carbon:time',
    'ui.chart': 'carbon:chart-bar',
    'ui.shield': 'carbon:security',
    'ui.chevron.left': 'carbon:chevron-left',
    'ui.chevron.down': 'carbon:chevron-down',
    'ui.chevron.right': 'carbon:chevron-right',
    'ui.chevron.up': 'carbon:chevron-up',
    'ui.wait': 'carbon:hourglass',
    'ui.minus': 'carbon:subtract',
    'ui.plus': 'carbon:add',
    'ui.help': 'carbon:help',
    'ui.star': 'carbon:star',
    'ui.moon': 'carbon:asleep',
    'ui.dino': 'carbon:game-console',
    'ui.refresh': 'carbon:renew',
    'ui.fullscreen': 'carbon:fit-to-screen',
    'ui.fullscreen.exit': 'carbon:minimize',
    'ui.menu': 'carbon:menu',
    'ui.notes': 'carbon:document',
    'ui.notes.multiple': 'carbon:document-multiple-01',
    'ui.chat': 'carbon:chat',
    'ui.sync': 'carbon:sync',
    'ui.checkbox.on': 'carbon:checkbox-checked',
    'ui.checkbox.off': 'carbon:checkbox',
    'ui.book': 'carbon:book',
    'ui.hint': 'carbon:information',
    'ui.calendar': 'carbon:calendar',
    'ui.sparkles': 'carbon:watson',
    'ui.drag': 'carbon:draggable',
    'ui.flame': 'carbon:flame',
    'ui.leaf': 'carbon:sprout',
    'ui.list.todo': 'carbon:task',
    'ui.list.checks': 'carbon:list',
    'ui.login': 'carbon:login',
    'ui.logout': 'carbon:logout',

    // Dashboard
    'dashboard.home': 'carbon:dashboard',
    'dashboard.plugins': 'carbon:flash',
    'dashboard.settings': 'carbon:settings',
    'dashboard.images': 'carbon:image',
    'dashboard.backup': 'carbon:export',
    'dashboard.restore': 'carbon:import',

    // Admin
    'admin.workspace': 'carbon:building',
    'admin.workspaces': 'carbon:enterprise',

    // Documents / Editor
    'editor.code': 'carbon:code',
    'editor.list': 'carbon:list',
    'editor.undo': 'carbon:undo',
    'editor.redo': 'carbon:redo',

    // Images
    'image.download': 'carbon:download',
    'image.copy': 'carbon:copy',
    'image.delete': 'carbon:trash-can',
    'image.repeat': 'carbon:renew',
    'image.multiple': 'carbon:image-copy',

    // Workflow Status
    'workflow.status.running': 'carbon:renew',
    'workflow.status.completed': 'carbon:checkmark',
    'workflow.status.error': 'carbon:close',
    'workflow.status.stopped': 'carbon:pause',
    'workflow.status.pending': 'carbon:time',

    // Notifications
    'notification.bell': 'carbon:notification',
    'notification.message': 'carbon:email',
    'notification.workflow': 'carbon:flash',
    'notification.sync': 'carbon:sync',
    'notification.warning': 'carbon:warning-alt',
    'notification.default': 'carbon:information',
    close: 'carbon:close',
};
