import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import * as Vue from 'vue';

const outputPath = resolve(import.meta.dirname, '../../public/_plugins/host-vue.mjs');

function exportNames(namespace: object): string[] {
    return Object.keys(namespace)
        .filter((name) => name !== 'default' && name !== '__esModule' && /^[A-Za-z_$][\w$]*$/.test(name))
        .sort();
}

export function renderHostVueFacade(namespace: object = Vue): string {
    const names = exportNames(namespace);
    return `// Generated by scripts/plugin-runtime/generate-host-vue-facade.ts.
// Re-exports every enumerable Vue binding from the host instance.
// or3-plugin-host-esm-facade:v1
// or3-plugin-vue-host-singleton:v1
const host = globalThis.__or3HostAbi?.vue;
if (!host) {
    throw new Error('OR3 host Vue singleton is not installed');
}

export const {
${names.map((name) => `    ${name},`).join('\n')}
} = host;

export default host;
`;
}

if (import.meta.main) {
    writeFileSync(outputPath, renderHostVueFacade());
    console.log(`[host-vue-facade] wrote ${exportNames(Vue).length} exports`);
}
