import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, extname, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

interface ModuleConfig {
    source: string;
}

interface LedgerConfig {
    nuxtImportsDeclaration: string;
    modules: ModuleConfig[];
}

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const configPath = resolve(repoRoot, 'planning/plugin-runtime-v2/compatibility-ledger.modules.json');
const snapshotDir = resolve(repoRoot, 'planning/plugin-runtime-v2/snapshots');
const publicApiSnapshot = resolve(snapshotDir, 'public-api.d.ts');
const nuxtImportsSnapshot = resolve(snapshotDir, 'nuxt-auto-imports.d.ts');
const tsconfigPath = resolve(repoRoot, '.nuxt/tsconfig.app.json');

function fail(message: string): never {
    throw new Error(`[compatibility-snapshots] ${message}`);
}

function posixPath(path: string): string {
    return path.split(sep).join('/');
}

function repoPath(path: string): string {
    return posixPath(relative(repoRoot, path));
}

function withoutExtension(path: string): string {
    const extension = extname(path);
    return extension ? path.slice(0, -extension.length) : path;
}

export function assertSnapshotEqual(label: string, expected: string, actual: string): void {
    if (expected === actual) return;
    const expectedLines = expected.split('\n');
    const actualLines = actual.split('\n');
    const maxLines = Math.max(expectedLines.length, actualLines.length);
    let differingLine = 0;
    while (differingLine < maxLines && expectedLines[differingLine] === actualLines[differingLine]) {
        differingLine += 1;
    }
    fail(`${label} snapshot mismatch at line ${differingLine + 1}; run \`bun run plugin-runtime:snapshots\` only after reviewing the V1 compatibility impact`);
}

function loadConfig(): LedgerConfig {
    return JSON.parse(readFileSync(configPath, 'utf8')) as LedgerConfig;
}

function loadCompilerOptions(): ts.CompilerOptions {
    if (!existsSync(tsconfigPath)) fail('missing .nuxt/tsconfig.app.json; run `bunx nuxt prepare`');
    const readResult = ts.readConfigFile(tsconfigPath, ts.sys.readFile);
    if (readResult.error) fail(ts.flattenDiagnosticMessageText(readResult.error.messageText, '\n'));
    const parsed = ts.parseJsonConfigFileContent(readResult.config, ts.sys, dirname(tsconfigPath));
    return {
        ...parsed.options,
        declaration: true,
        declarationMap: false,
        emitDeclarationOnly: true,
        noEmit: false,
    };
}

function generatePublicApiSnapshot(config: LedgerConfig): string {
    const modulePaths = config.modules.map((module) => resolve(repoRoot, module.source));
    const program = ts.createProgram({ rootNames: modulePaths, options: loadCompilerOptions() });
    const sections: string[] = [
        '// Generated by scripts/plugin-runtime/generate-compatibility-snapshots.ts.',
        '// Review changes as V1 compatibility changes; do not edit by hand.',
    ];
    for (const module of [...config.modules].sort((a, b) => a.source.localeCompare(b.source))) {
        const sourceFile = program.getSourceFile(resolve(repoRoot, module.source));
        if (!sourceFile) fail(`TypeScript program did not load ${module.source}`);
        const emitted: Array<{ fileName: string; text: string }> = [];
        const result = program.emit(
            sourceFile,
            (fileName, text) => emitted.push({ fileName, text }),
            undefined,
            true,
        );
        if (result.emitSkipped || emitted.length !== 1) {
            const diagnostics = ts.formatDiagnosticsWithColorAndContext(result.diagnostics, {
                getCanonicalFileName: (fileName) => fileName,
                getCurrentDirectory: () => repoRoot,
                getNewLine: () => '\n',
            });
            fail(`declaration emit failed for ${module.source}${diagnostics ? `\n${diagnostics}` : ''}`);
        }
        sections.push(`\n// ---- ${module.source} ----\n${emitted[0]!.text.trimEnd()}`);
    }
    return `${sections.join('\n')}\n`;
}

function declarationSections(path: string, moduleSources: Set<string>): string[] {
    if (!existsSync(path)) fail(`missing generated Nuxt declaration: ${repoPath(path)}`);
    const sourceFile = ts.createSourceFile(path, readFileSync(path, 'utf8'), ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
    const sections: string[] = [];
    for (const statement of sourceFile.statements) {
        if (!ts.isExportDeclaration(statement) || !statement.moduleSpecifier || !ts.isStringLiteral(statement.moduleSpecifier)) continue;
        const specifier = statement.moduleSpecifier.text;
        if (!specifier.startsWith('.')) continue;
        const resolvedSource = withoutExtension(resolve(dirname(path), specifier));
        if (moduleSources.has(resolvedSource)) sections.push(statement.getText(sourceFile));
    }
    return sections;
}

function generateNuxtImportsSnapshot(config: LedgerConfig): string {
    const moduleSources = new Set(config.modules.map((module) => withoutExtension(resolve(repoRoot, module.source))));
    const exportsPath = resolve(repoRoot, config.nuxtImportsDeclaration);
    const globalTypesPath = resolve(repoRoot, '.nuxt/types/imports.d.ts');
    const exportSections = declarationSections(exportsPath, moduleSources);
    if (!exportSections.length) fail('no plugin-facing exports found in generated Nuxt imports declaration');
    if (!existsSync(globalTypesPath)) fail('missing .nuxt/types/imports.d.ts; run `bunx nuxt prepare`');

    const moduleNeedles = config.modules.map((module) => withoutExtension(module.source));
    const globalLines = readFileSync(globalTypesPath, 'utf8').split('\n').filter((line) =>
        moduleNeedles.some((source) => line.includes(source)),
    );
    if (!globalLines.length) fail('no plugin-facing globals found in generated Nuxt imports declaration');

    return [
        '// Generated by scripts/plugin-runtime/generate-compatibility-snapshots.ts.',
        '// Scoped to modules in compatibility-ledger.modules.json.',
        '',
        '// ---- .nuxt/imports.d.ts ----',
        ...exportSections.sort(),
        '',
        '// ---- .nuxt/types/imports.d.ts ----',
        ...globalLines.sort(),
        '',
    ].join('\n');
}

function writeOrCheck(path: string, content: string, checkOnly: boolean): void {
    if (checkOnly) {
        if (!existsSync(path)) fail(`missing snapshot: ${repoPath(path)}`);
        assertSnapshotEqual(repoPath(path), readFileSync(path, 'utf8'), content);
        return;
    }
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
}

function main() {
    const checkOnly = process.argv.includes('--check');
    const config = loadConfig();
    const publicApi = generatePublicApiSnapshot(config);
    const nuxtImports = generateNuxtImportsSnapshot(config);
    writeOrCheck(publicApiSnapshot, publicApi, checkOnly);
    writeOrCheck(nuxtImportsSnapshot, nuxtImports, checkOnly);
    console.log(`[compatibility-snapshots] ${checkOnly ? 'verified' : 'wrote'} public API and Nuxt auto-import snapshots`);
}

if (import.meta.main) main();
