/**
 * Auto-generated by theme compiler
 * Do not edit manually - changes will be overwritten
 * Generated: 2025-11-07T01:01:36.110Z
 */

/**
 * Available theme names
 */
export type ThemeName = 'nature' | 'retro';

/**
 * Available theme identifiers for v-theme directive
 */
export type ThemeIdentifier = 'chat.send' | 'sidebar.toggle' | 'sidebar.filter' | 'chat.stop' | 'chat.attach' | 'chat.settings' | 'chat.editor' | 'message.copy' | 'message.retry' | 'message.branch' | 'message.edit' | 'settings.thinking' | 'dashboard.export' | 'dashboard.import' | 'document.toolbar' | 'document.search';

/**
 * Available context names
 */
export type ThemeContext = 'chat' | 'document' | 'sidebar' | 'dashboard' | 'header' | 'global' | 'settings' | 'shell' | 'message' | 'modal';

/**
 * Theme directive value
 */
export interface ThemeDirective {
    /** Theme identifier */
    identifier?: ThemeIdentifier;
    
    /** Theme name to use */
    theme?: ThemeName;
    
    /** Context override */
    context?: ThemeContext;
}

/**
 * String shorthand for theme directive (just the identifier)
 */
export type ThemeDirectiveValue = ThemeIdentifier | ThemeDirective;
