/**
 * Auto-generated by theme compiler
 * Do not edit manually - changes will be overwritten
 * Generated: 2026-02-05T00:27:52.353Z
 */

/**
 * Available theme names
 */
export type ThemeName = 'test';

/**
 * Available theme identifiers for v-theme directive
 */
export type ThemeIdentifier = string;

/**
 * Available context names
 */
export type ThemeContext = 'chat' | 'sidebar' | 'dashboard' | 'header' | 'global' | 'settings' | 'shell' | 'message' | 'modal' | 'document' | 'image-viewer' | 'images' | 'prompt' | 'docs' | 'ui';

/**
 * Theme directive value
 */
export interface ThemeDirective {
    /** Theme identifier */
    identifier?: ThemeIdentifier;
    
    /** Theme name to use */
    theme?: ThemeName;
    
    /** Context override */
    context?: ThemeContext;
}

/**
 * String shorthand for theme directive (just the identifier)
 */
export type ThemeDirectiveValue = ThemeIdentifier | ThemeDirective;
