/**
 * Auto-generated by theme compiler
 * Do not edit manually - changes will be overwritten
 * Generated: 2026-01-11T08:33:22.963Z
 */

/**
 * Available theme names
 */
export type ThemeName = 'blank' | 'retro';

/**
 * Available theme identifiers for v-theme directive
 */
export type ThemeIdentifier = 'sidebar.header' | 'sidebar.bottom-nav.connect' | 'sidebar.collapsed-page' | 'shell.pane-close' | 'chat.scroll-to-bottom' | 'message.reasoning-toggle' | 'chat.send' | 'chat.stop' | 'chat.editor' | 'chat.input-main-container' | 'chat.attach' | 'chat.settings' | 'chat.model-select' | 'dashboard.shell' | 'message.user-container' | 'sidebar.filter' | 'sidebar.filter-item' | 'sidebar.search' | 'sidebar.project-select' | 'ui.glass-button' | 'sidebar.project-group-container' | 'sidebar.new-chat' | 'sidebar.thread-rename' | 'sidebar.thread-add-to-project' | 'sidebar.thread-delete' | 'sidebar.thread-extra-action' | 'sidebar.document-rename' | 'sidebar.document-add-to-project' | 'sidebar.document-delete' | 'sidebar.document-extra-action' | 'sidebar.project-rename' | 'sidebar.project-delete' | 'sidebar.project-extra-action' | 'sidebar.bottom-nav.info' | 'sidebar.bottom-nav.dashboard' | 'sidebar.bottom-nav.activity' | 'sidebar.bottom-nav.credits' | 'dashboard.back' | 'images.gallery.download' | 'images.gallery.copy' | 'images.delete' | 'images.delete-selection' | 'sidebar.toggle' | 'dashboard.theme.copy-color' | 'dashboard.workspace.import-mode';

/**
 * Available context names
 */
export type ThemeContext = 'message' | 'settings' | 'image-viewer' | 'document' | 'chat' | 'sidebar' | 'dashboard' | 'header' | 'global' | 'shell' | 'modal' | 'images' | 'prompt' | 'docs' | 'ui';

/**
 * Theme directive value
 */
export interface ThemeDirective {
    /** Theme identifier */
    identifier?: ThemeIdentifier;
    
    /** Theme name to use */
    theme?: ThemeName;
    
    /** Context override */
    context?: ThemeContext;
}

/**
 * String shorthand for theme directive (just the identifier)
 */
export type ThemeDirectiveValue = ThemeIdentifier | ThemeDirective;
