export const DEFAULT_ICONS = {
    // Shell & Navigation
    'shell.sidebar.toggle.left': 'pixelarticons:arrow-bar-left',
    'shell.sidebar.toggle.right': 'pixelarticons:arrow-bar-right',
    'shell.pane.add': 'pixelarticons:card-plus',
    'shell.pane.close': 'pixelarticons:close',
    'shell.theme.light': 'pixelarticons:sun',
    'shell.theme.dark': 'pixelarticons:moon-star',
    'shell.menu': 'pixelarticons:more-vertical',
    'shell.back': 'pixelarticons:arrow-left',
    'shell.expand': 'i-lucide:folder-open',
    'shell.collapse': 'i-lucide:folder',
    'shell.tab.new': 'i-lucide:plus',
    'shell.tabs': 'i-lucide:copy',
    'shell.tabs.search': 'i-lucide:search',

    // Chat Interface
    'chat.send': 'pixelarticons:arrow-up',
    'chat.stop': 'pixelarticons:pause',
    'chat.attach': 'i-lucide:plus',
    'chat.upload': 'i-lucide:upload-cloud',
    'chat.clear': 'i-lucide:x',
    'chat.model.search': 'pixelarticons:search',
    'chat.model.settings': 'pixelarticons:sliders',
    'chat.model.catalog': 'pixelarticons:android',
    'chat.system_prompt': 'pixelarticons:script-text',
    'chat.web_search': 'pixelarticons:globe',
    'chat.scrollToBottom': 'pixelarticons:arrow-bar-down',

    // Chat Messages
    'chat.message.copy': 'pixelarticons:copy',
    'chat.message.retry': 'pixelarticons:reload',
    'chat.message.edit': 'pixelarticons:edit-box',
    'chat.message.branch': 'pixelarticons:git-branch',
    'chat.message.continue': 'pixelarticons:play',
    'chat.message.delete': 'pixelarticons:trash',
    'chat.reasoning': 'pixelarticons:lightbulb-on',

    // Tool Indicators
    'chat.tool.loader': 'pixelarticons:loader',
    'chat.tool.check': 'pixelarticons:check',
    'chat.tool.error': 'pixelarticons:close',
    'chat.tool.wrench': 'pixelarticons:wrench',

    // Sidebar
    'sidebar.search': 'pixelarticons:search',
    'sidebar.new_chat': 'pixelarticons:message-plus',
    'sidebar.new_folder': 'pixelarticons:folder-plus',
    'sidebar.new_note': 'pixelarticons:note-plus',
    'sidebar.edit': 'pixelarticons:edit',
    'sidebar.delete': 'pixelarticons:trash',
    'sidebar.folder': 'pixelarticons:folder',
    'sidebar.chat': 'pixelarticons:chat',
    'sidebar.note': 'pixelarticons:note',
    'sidebar.settings': 'pixelarticons:sliders',
    'sidebar.user': 'pixelarticons:user',
    'sidebar.activity': 'pixelarticons:human-run',
    'sidebar.credits': 'pixelarticons:coin',
    'sidebar.project.root': 'pixelarticons:home',
    'sidebar.page.home': 'pixelarticons:home',
    'sidebar.page.messages': 'pixelarticons:comment',
    'sidebar.page.default': 'pixelarticons:view-grid',

    // Common UI
    'ui.check': 'pixelarticons:check',
    'ui.close': 'pixelarticons:close',
    'ui.copy': 'pixelarticons:copy',
    'ui.trash': 'pixelarticons:trash',
    'ui.edit': 'pixelarticons:edit',
    'ui.warning': 'pixelarticons:warning-box',
    'ui.info': 'pixelarticons:info-box',
    'ui.loading': 'pixelarticons:loader',
    'ui.more': 'pixelarticons:more-vertical',
    'ui.download': 'pixelarticons:download',
    'ui.upload': 'pixelarticons:cloud-upload',
    'ui.search': 'pixelarticons:search',
    'ui.filter': 'pixelarticons:list',
    'ui.sort': 'pixelarticons:sort',
    'ui.view': 'pixelarticons:eye',
    'ui.view_off': 'pixelarticons:eye-closed',
    'ui.lock': 'pixelarticons:lock',
    'ui.unlock': 'pixelarticons:lock-open',
    'ui.settings': 'pixelarticons:sliders',
    'ui.unknown': 'pixelarticons:alert',
    'ui.clock': 'pixelarticons:clock',
    'ui.chart': 'pixelarticons:chart-bar',
    'ui.shield': 'pixelarticons:shield',
    'ui.login': 'pixelarticons:login',
    'ui.logout': 'pixelarticons:logout',
    'ui.chevron.left': 'pixelarticons:chevron-left',
    'ui.arrow.left': 'pixelarticons:arrow-left',
    'ui.chevron.right': 'pixelarticons:chevron-right',
    'ui.chevron.up': 'pixelarticons:chevron-up',
    'ui.chevron.down': 'pixelarticons:chevron-down',
    'ui.calendar': 'pixelarticons:calendar',
    'ui.sparkles': 'pixel:sparkles',
    'ui.drag': 'pixelarticons:drag-and-drop',
    'ui.flame': 'pixel:fire-solid',
    'ui.leaf': 'pixel:seedlings-solid',
    'ui.list.todo': 'pixelarticons:checklist',
    'ui.list.checks': 'pixelarticons:list',
    'ui.tasklist': 'pixel:check-list-solid',
    'ui.wait': 'pixelarticons:hourglass',
    'ui.minus': 'pixelarticons:minus',
    'ui.plus': 'pixelarticons:plus',
    'ui.help': 'pixelarticons:message-processing',
    'ui.star': 'pixelarticons:star',
    'ui.moon': 'pixelarticons:moon-stars',
    'ui.dino': 'pixelarticons:downasaur',
    'ui.refresh': 'pixelarticons:reload',
    'ui.fullscreen': 'material-symbols:fullscreen',
    'ui.fullscreen.exit': 'material-symbols:fullscreen-exit',
    'ui.menu': 'pixelarticons:menu',
    'ui.notes': 'pixelarticons:notes',
    'ui.notes.multiple': 'pixelarticons:notes-multiple',
    'ui.chat': 'pixelarticons:message-text',
    'ui.sync': 'pixelarticons:sync',
    'ui.checkbox.on': 'pixelarticons:checkbox-on',
    'ui.checkbox.off': 'pixelarticons:checkbox',
    'ui.book': 'pixelarticons:book',
    'ui.hint': 'pixelarticons:info-box',

    // Dashboard
    'dashboard.home': 'pixelarticons:dashboard',
    'dashboard.plugins': 'pixelarticons:zap',
    'dashboard.settings': 'pixelarticons:sliders',
    'dashboard.images': 'pixelarticons:image',
    'dashboard.backup': 'pixelarticons:briefcase-download',
    'dashboard.restore': 'pixelarticons:briefcase-upload',

    // Command palette
    'palette.search': 'pixelarticons:search',
    'palette.command': 'pixelarticons:zap',
    'palette.chat': 'pixelarticons:chat',
    'palette.document': 'pixelarticons:note',
    'palette.project': 'pixelarticons:folder',
    'palette.prompt': 'pixelarticons:script-text',
    'palette.workflow': 'pixelarticons:git-branch',
    'palette.image': 'pixelarticons:image',
    'palette.setting': 'pixelarticons:sliders',
    'palette.dashboard': 'pixelarticons:dashboard',
    'palette.recent': 'pixelarticons:clock',
    'palette.result': 'pixelarticons:chevron-right',
    'palette.new-pane': 'pixelarticons:card-plus',

    // Admin
    'admin.workspace': 'pixelarticons:building',
    'admin.workspaces': 'pixelarticons:buildings',

    // Documents / Editor
    'editor.document': 'pixelarticons:note',
    'editor.search': 'pixelarticons:search',
    'editor.inspector': 'pixelarticons:layout-columns',
    'editor.more': 'pixelarticons:more-vertical',
    'editor.close': 'pixelarticons:close',
    'editor.previous': 'pixelarticons:chevron-up',
    'editor.next': 'pixelarticons:chevron-down',
    'editor.ai': 'pixel:sparkles',
    'editor.outline': 'pixelarticons:list',
    'editor.history': 'pixelarticons:clock',
    'editor.info': 'pixelarticons:info-box',
    'editor.plugin': 'pixelarticons:zap',
    'editor.settings': 'pixelarticons:sliders',
    'editor.send': 'pixelarticons:arrow-up',
    'editor.stop': 'pixelarticons:pause',
    'editor.format.bold': 'lucide:bold',
    'editor.format.italic': 'lucide:italic',
    'editor.format.underline': 'lucide:underline',
    'editor.format.strike': 'lucide:strikethrough',
    'editor.format.link': 'lucide:link',
    'editor.format.quote': 'lucide:quote',
    'editor.format.bullet-list': 'lucide:list',
    'editor.format.ordered-list': 'lucide:list-ordered',
    'editor.format.task-list': 'lucide:list-checks',
    'editor.insert.text': 'lucide:type',
    'editor.insert.heading-1': 'lucide:heading-1',
    'editor.insert.heading-2': 'lucide:heading-2',
    'editor.insert.code-block': 'lucide:square-code',
    'editor.insert.divider': 'lucide:minus',
    'editor.insert.table': 'lucide:table-2',
    'editor.insert.image': 'lucide:image-plus',
    'editor.code': 'pixelarticons:code',
    'editor.list': 'pixelarticons:list',
    'editor.undo': 'pixelarticons:undo',
    'editor.redo': 'pixelarticons:redo',

    // Images
    'image.download': 'pixelarticons:download',
    'image.copy': 'pixelarticons:copy',
    'image.delete': 'pixelarticons:image-delete',
    'image.repeat': 'pixelarticons:repeat',
    'image.multiple': 'pixelarticons:image-multiple',

    // Workflow Status
    'workflow.status.running': 'pixelarticons:loader',
    'workflow.status.completed': 'pixelarticons:check',
    'workflow.status.error': 'pixelarticons:close',
    'workflow.status.stopped': 'pixelarticons:pause',
    'workflow.status.pending': 'pixelarticons:clock',

    // Notifications
    'notification.bell': 'pixelarticons:notification',
    'notification.message': 'pixelarticons:message',
    'notification.workflow': 'pixelarticons:zap',
    'notification.sync': 'pixelarticons:sync',
    'notification.warning': 'pixelarticons:warning-box',
    'notification.default': 'pixelarticons:info-box',

    // Model Catalog
    'catalog.all': 'tabler:layout-grid',
    'catalog.star': 'tabler:star',
    'catalog.star.filled': 'tabler:star-filled',
    'catalog.filter': 'tabler:filter',
    'catalog.sort': 'tabler:arrows-sort',
    'catalog.text': 'tabler:typography',
    'catalog.vision': 'tabler:eye',
    'catalog.tools': 'tabler:tool',
    'catalog.reasoning': 'tabler:brain',
    'catalog.json': 'tabler:braces',
    'catalog.embedding': 'tabler:vector',
    'catalog.context': 'tabler:database',
    'catalog.image': 'tabler:photo',
    'catalog.coin': 'tabler:coin',
    'catalog.calendar': 'tabler:calendar-event',
    'catalog.info': 'tabler:info-circle',
    'catalog.external': 'tabler:external-link',
    'catalog.back': 'tabler:arrow-left',
    'catalog.sparkles': 'tabler:sparkles',
    'catalog.category': 'tabler:category',
    'catalog.building': 'tabler:building',
    close: 'pixelarticons:close',
} as const;

export type IconToken = keyof typeof DEFAULT_ICONS;
