<template>
    <section class="space-y-2 rounded-[var(--md-border-radius)] border border-[var(--md-outline-variant)] bg-[var(--md-surface)] p-3" aria-label="Context compacted" :aria-busy="opening" data-compaction-card>
        <details @toggle="emit('content-resize')">
            <summary class="cursor-pointer min-h-11 py-2 font-medium">
                Context compacted
                <span class="text-sm font-normal text-[var(--md-on-surface-variant)]">
                    · {{ coveredCount }} messages · {{ compaction.landmarks.length }} {{ compaction.landmarks.length === 1 ? 'landmark' : 'landmarks' }}
                </span>
            </summary>
            <p class="mb-2 text-sm text-[var(--md-on-surface-variant)]">Historical reference generated by {{ compaction.model }}. Verify details in the original conversation.</p>
            <div class="whitespace-pre-wrap break-words text-sm" data-compaction-summary>{{ compaction.summary_markdown }}</div>
            <ul v-if="compaction.landmarks.length" class="mt-3 space-y-1" aria-label="Historical landmarks">
                <li v-for="landmark in compaction.landmarks" :key="landmark.message_id">
                    <UButton color="neutral" variant="link" class="min-h-11 whitespace-normal text-left" :disabled="opening" @click="openTarget(landmark.thread_id, landmark.message_id)">
                        {{ landmark.summary }}
                    </UButton>
                </li>
            </ul>
            <p v-if="retrievalAvailable === false" class="mt-2 text-sm text-[var(--md-on-surface-variant)]">Historical retrieval tools are unavailable for this model or tool selection. You can still follow the original and landmark links.</p>
        </details>
        <UButton color="neutral" variant="soft" class="min-h-11" :disabled="opening" @click="openTarget(compaction.source_thread_id, compaction.anchor_message_id)">View original<span v-if="sourceOrdinal"> · message {{ sourceOrdinal }}</span></UButton>
        <p v-if="unavailable" role="status" class="text-sm text-[var(--md-on-surface-variant)]">{{ unavailable }}</p>
    </section>
</template>

<script setup lang="ts">
import { computed, shallowRef, watch, onBeforeUnmount } from 'vue';
import Dexie, { liveQuery, type Subscription } from 'dexie';
import { getDb, getWorkspaceGeneration, subscribeActiveWorkspaceDb } from '~/db/client';
import { storedMessagesToCanonicalTranscript, isSupersededMessage } from '~/utils/chat/transcript';
import { compareMessageOrder } from '~/db/messages';
import type { UiChatMessage } from '~/utils/chat/uiMessages';
import type { CompactionData } from '~~/shared/chat/compaction';

const props = defineProps<{ message: UiChatMessage & { compaction: CompactionData }; threadId?: string; retrievalAvailable?: boolean }>();
const emit = defineEmits<{
    (e: 'view-compaction-source', target: { threadId: string; messageId: string; originThreadId: string; scrollMessageId?: string }): void;
    (e: 'content-resize'): void;
}>();
const compaction = computed(() => props.message.compaction);
const coveredCount = computed(() => (BigInt(compaction.value.message_count) + BigInt(compaction.value.prior_message_count)).toLocaleString());
const opening = shallowRef(false);
const unavailable = shallowRef<string>();
const sourceOrdinal = shallowRef<number>();
let ordinalSubscription: Subscription | undefined;
let revision = 0;
let renderedDb = getDb();
let disposed = false;
function invalidate() { revision += 1; opening.value = false; unavailable.value = undefined; bindOrdinal(); }
watch(() => props.threadId, invalidate, { flush: 'sync' });
watch([() => props.message, () => props.message.compaction], () => { renderedDb = getDb(); invalidate(); }, { flush: 'sync' });
const unsubscribe = subscribeActiveWorkspaceDb(invalidate);
onBeforeUnmount(() => { disposed = true; revision += 1; unsubscribe(); ordinalSubscription?.unsubscribe(); });

function bindOrdinal() {
    ordinalSubscription?.unsubscribe(); sourceOrdinal.value = undefined;
    if (getDb() !== renderedDb) return;
    const db = renderedDb; const generation = getWorkspaceGeneration(); const token = revision;
    const source = compaction.value.source_thread_id; const anchorId = compaction.value.anchor_message_id;
    ordinalSubscription = liveQuery(async () => {
        let thread = await db.threads.get(source); let anchor = await db.messages.get(anchorId);
        if (!thread || thread.deleted || !anchor || anchor.deleted || anchor.thread_id !== source || isSupersededMessage(anchor)) return undefined;
        if (anchor.role === 'tool') {
            const tool = storedMessagesToCanonicalTranscript([anchor])[0];
            const parent = tool?.parentAssistantId ? await db.messages.get(tool.parentAssistantId) : undefined;
            const parentRecord = parent && storedMessagesToCanonicalTranscript([parent, anchor]).find((row) => row.id === parent.id);
            if (!parent || parent.deleted || parent.role !== 'assistant' || parent.thread_id !== source || isSupersededMessage(parent)
                || !tool?.callId || !parentRecord?.toolCalls.some((call) => call.callId === tool.callId)) return undefined;
            anchor = parent;
        }
        let ordinal = 0; const visited = new Set<string>();
        for (;;) {
            if (!thread || thread.deleted || visited.has(thread.id)) return undefined;
            visited.add(thread.id);
            const boundary = anchor;
            ordinal += await db.messages.where('[thread_id+index]')
                .between([thread.id, Dexie.minKey], [thread.id, boundary.index], true, true)
                .filter((row) => compareMessageOrder(row, boundary) <= 0 && !row.deleted && row.role !== 'tool' && !isSupersededMessage(row)).count();
            if (thread.branch_mode !== 'reference') return ordinal;
            if (!thread.parent_thread_id || !thread.anchor_message_id) return undefined;
            anchor = await db.messages.get(thread.anchor_message_id);
            if (!anchor || anchor.deleted || anchor.thread_id !== thread.parent_thread_id) return undefined;
            thread = await db.threads.get(thread.parent_thread_id);
        }
    }).subscribe({ next: (ordinal) => {
        if (!disposed && token === revision && db === getDb() && generation === getWorkspaceGeneration()) sourceOrdinal.value = ordinal;
    }, error: () => { if (token === revision) sourceOrdinal.value = undefined; } });
}
bindOrdinal();

async function openTarget(threadId: string, messageId: string) {
    if (opening.value) return;
    if (getDb() !== renderedDb) { unavailable.value = 'This summary belongs to the previous workspace. Open its conversation in that workspace.'; return; }
    const originThreadId = props.threadId;
    if (!originThreadId) { unavailable.value = 'Open this compacted conversation before following its original links.'; return; }
    const db = getDb(); const generation = getWorkspaceGeneration(); const capturedRevision = revision;
    const current = () => !disposed && revision === capturedRevision && props.threadId === originThreadId && getDb() === db && getWorkspaceGeneration() === generation;
    opening.value = true; unavailable.value = undefined;
    try {
        const [thread, message] = await Promise.all([db.threads.get(threadId), db.messages.get(messageId)]);
        if (!current()) return;
        if (!thread || thread.deleted || !message || message.deleted || message.thread_id !== threadId || isSupersededMessage(message)) {
            unavailable.value = 'This original message is unavailable. It may have been deleted or replaced.';
            return;
        }
        let scrollMessageId: string | undefined;
        if (message.role === 'tool') {
            const tool = storedMessagesToCanonicalTranscript([message])[0]!;
            const parent = tool.parentAssistantId ? await db.messages.get(tool.parentAssistantId) : undefined;
            if (!current()) return;
            const parentRecord = parent && storedMessagesToCanonicalTranscript([parent, message]).find((row) => row.id === parent.id);
            if (!parent || parent.deleted || parent.thread_id !== threadId || parent.role !== 'assistant' || isSupersededMessage(parent)
                || !tool.callId || !parentRecord?.toolCalls.some((call) => call.callId === tool.callId)) {
                unavailable.value = 'This original tool evidence is unavailable. Its visible assistant reply may have been deleted or replaced.';
                return;
            }
            scrollMessageId = parent.id;
        }
        emit('view-compaction-source', { threadId, messageId, originThreadId, ...(scrollMessageId ? { scrollMessageId } : {}) });
    } catch {
        if (current()) unavailable.value = 'The original conversation could not be opened. Try again when it is available.';
    } finally { if (current()) opening.value = false; }
}
</script>
