// Generated by scripts/plugin-runtime/generate-compatibility-snapshots.ts.
// Scoped to modules in compatibility-ledger.modules.json.

// ---- .nuxt/imports.d.ts ----
export { EditorInstance, OpenRouterMessage, AiSendBeforePayload, AiSendAfterPayloadTimings, AiSendAfterPayload, AiStreamDeltaContext, AiStreamReasoningContext, AiStreamCompleteContext, AiStreamErrorContext, AiStreamDeltaPayload, AiStreamReasoningPayload, AiStreamCompletePayload, AiStreamErrorPayload, AiRetryBeforePayload, AiRetryAfterPayload, UiPaneMsgBase, UiPaneMsgReceived, UiPaneActivePayload, UiPaneBlurPayload, UiPaneSwitchPayload, UiPaneThreadChangedPayload, UiPaneDocChangedPayload, UiPaneMsgSentPayload, UiPaneMsgReceivedPayload, UiSidebarSelectPayload, UiChatNewPayload, AppInitPayload, FilesAttachPayload, FilesAttachInputPayload, BranchMode, BranchForkOptions, RetryBranchParams, BranchForkBeforePayload, BranchContextAfterPayload, KvUpsertByNameInput, MessageEntity, MessageCreateEntity, ThreadEntity, ThreadCreateEntity, DocumentEntity, FileEntity, ProjectEntity, PostEntity, PostCreateEntity, PromptEntity, AttachmentEntity, KvEntry, Permission, WorkspaceRole, AccessDecision, SessionContext, SyncScopePayload, SyncPendingOpPayload, NotificationAction, NotificationCreatePayload, NotificationEntity, StorageFileUploadBeforePayload, StorageFileUploadAfterPayload, StorageFileDownloadBeforePayload, StorageFileDownloadAfterPayload, StorageFileUrlOptionsPayload, StorageFileUploadPolicyPayload, StorageFileGcPayload, DbCreatePayload, DbUpdatePayload, DbDeletePayload, DbEntityName, DbOperation, DbPhase, DbDeleteType, DbActionHookName, DbFilterHookName, CoreActionHookName, ExtensionActionHookName, ActionHookName, CoreFilterHookName, ExtensionFilterHookName, FilterHookName, HookName, CoreHookPayloadMap, HookPayloadMap, InferHookParams, InferHookReturn, InferHookCallback, IsAction, IsFilter, ExtractHookPayload, MatchingHooks, InferDbEntity, InferDbCreateEntity, Tail, SuggestSimilar, ValidateHookName, TypeName, CallbackMismatch } from '../app/core/hooks/hook-types';
export { SidebarPageControlsKey, provideSidebarPageControls, SidebarEnvironmentKey, createSidebarMultiPaneApi, provideSidebarEnvironment, useSidebarEnvironment, useSidebarProjects, useSidebarThreads, useSidebarDocuments, useSidebarQuery, useActiveSections, useExpandedProjects, useActiveThreadIds, useActiveDocumentIds, useSidebarMultiPane, useSidebarPostsApi, SidebarPageControls, SidebarMultiPaneApi, SidebarEnvironment } from '../app/composables/sidebar/useSidebarEnvironment';
export { createHistoryActionRegistry, HistoryActionRegistryItem } from '../app/composables/history/createHistoryActionRegistry';
export { createHookEngine, HookFn, HookEngine, HookKind, OnOptions, RegisterOptions } from '../app/core/hooks/hooks';
export { createTypedHookEngine, TypedHookEngine } from '../app/core/hooks/typed-hooks';
export { createWorkspacePluginApi, registerWorkspacePluginInstance, unregisterWorkspacePluginInstance, listWorkspacePluginInstances, WorkspacePluginSource, Or3WorkspacePluginApi, Or3WorkspacePlugin } from '../app/composables/plugins/workspace-runtime';
export { default as registerSidebarPage, registerSidebarPageWithPosts, RegisterSidebarPageOptions, RegisterSidebarPageWithPostsOptions } from '../app/composables/sidebar/registerSidebarPage';
export { loadEditorExtensions, createLazyNodeFactory, createLazyMarkFactory, createLazyExtensionFactory, LazyEditorNodeFactory, LazyEditorMarkFactory, LazyEditorExtensionFactory, EditorNodeDescriptor, EditorMarkDescriptor, EditorExtensionDescriptor, LoadedExtensions } from '../app/composables/editor/useEditorExtensionLoader';
export { registerComposerAction, unregisterComposerAction, useComposerActions, listRegisteredComposerActionIds, ComposerActionContext, ComposerAction, ComposerActionEntry } from '../app/composables/sidebar/useComposerActions';
export { registerDashboardPlugin, unregisterDashboardPlugin, useDashboardPlugins, listRegisteredDashboardPluginIds, registerDashboardPluginPage, unregisterDashboardPluginPage, useDashboardPluginPages, listDashboardPluginPages, getDashboardPluginPage, resolveDashboardPluginPageComponent, useDashboardNavigation, hasCapability, getPluginCapabilities, hasAllCapabilities, hasAnyCapability, DashboardPlugin, DashboardPluginPage, DashboardNavigationErrorCode, DashboardNavigationError, DashboardNavigationState, DashboardNavigationResult, UseDashboardNavigationOptions } from '../app/composables/dashboard/useDashboardPlugins';
export { registerDocumentHistoryAction, unregisterDocumentHistoryAction, useDocumentHistoryActions, listRegisteredDocumentHistoryActionIds, DocumentHistoryAction } from '../app/composables/documents/useDocumentHistoryActions';
export { registerEditorNode, unregisterEditorNode, registerEditorMark, unregisterEditorMark, registerEditorExtension, unregisterEditorExtension, listEditorNodes, listEditorMarks, listEditorExtensions, listRegisteredEditorNodeIds, listRegisteredEditorMarkIds, listRegisteredEditorExtensionIds, EditorNode, EditorMark, EditorExtension } from '../app/composables/editor/useEditorNodes';
export { registerEditorToolbarButton, unregisterEditorToolbarButton, useEditorToolbarButtons, listRegisteredEditorToolbarButtonIds, EditorToolbarButton } from '../app/composables/editor/useEditorToolbar';
export { registerHeaderAction, unregisterHeaderAction, useHeaderActions, listRegisteredHeaderActionIds, HeaderActionContext, HeaderAction, HeaderActionEntry } from '../app/composables/sidebar/useHeaderActions';
export { registerMessageAction, unregisterMessageAction, useMessageActions, listRegisteredMessageActionIds, ChatMessageAction } from '../app/composables/chat/useMessageActions';
export { registerProjectTreeAction, unregisterProjectTreeAction, useProjectTreeActions, listRegisteredProjectTreeActionIds, ProjectTreeKind, ShowOnKind, ProjectTreeChild, ProjectTreeRoot, ProjectTreeRow, ProjectTreeHandlerCtx, ProjectTreeAction } from '../app/composables/projects/useProjectTreeActions';
export { registerSidebarSection, unregisterSidebarSection, registerSidebarFooterAction, unregisterSidebarFooterAction, useSidebarSections, useSidebarFooterActions, listRegisteredSidebarSectionIds, listRegisteredSidebarFooterActionIds, SidebarSectionPlacement, SidebarSection, SidebarSectionGroups, SidebarFooterActionContext, ChromeActionColor, SidebarFooterAction, SidebarFooterActionEntry } from '../app/composables/sidebar/useSidebarSections';
export { registerThreadHistoryAction, unregisterThreadHistoryAction, useThreadHistoryActions, listRegisteredThreadHistoryActionIds, ThreadHistoryAction } from '../app/composables/threads/useThreadHistoryActions';
export { state, registerAdminPage, registerAdminWidget, useAdminPages, useAdminWidgets, resolveAdminComponent, createAdminPluginApi, loadAdminPlugins, AdminPageDef, AdminWidgetDef, AdminComponent, AdminPlugin, AdminPluginApi } from '../app/composables/admin/useAdminPlugins';
export { typedOn, KnownHookKey, DbFamily, DbHookKey, HookKey, ChatOutgoingFilterReturn, ChatIncomingFilterReturn, FilesAttachFilterReturn } from '../app/core/hooks/hook-keys';
export { useGlobalRegistry, createRegistry, RegistryItem, RegistryApi, RegistrationHandle } from '../app/composables/_registry';
export { useHookEffect } from '../app/composables/core/useHookEffect';
export { useHooks } from '../app/core/hooks/useHooks';
export { usePaneApps, PaneAppDef, RegisteredPaneApp } from '../app/composables/core/usePaneApps';
export { useSidebarPageControls, useIsActivePage, useActivePageId, useSwitchToPage, useResetToDefaultPage, useSidebarPageState } from '../app/composables/sidebar/useSidebarPageControls';
export { useSidebarPages, SidebarPageDef, SidebarPageContext, SidebarActivateContext, RegisteredSidebarPage } from '../app/composables/sidebar/useSidebarPages';

// ---- .nuxt/types/imports.d.ts ----
    readonly SidebarEnvironmentKey: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarEnvironment')['SidebarEnvironmentKey']>
    readonly SidebarPageControlsKey: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarEnvironment')['SidebarPageControlsKey']>
    readonly createAdminPluginApi: UnwrapRef<typeof import('../../app/composables/admin/useAdminPlugins')['createAdminPluginApi']>
    readonly createHistoryActionRegistry: UnwrapRef<typeof import('../../app/composables/history/createHistoryActionRegistry')['createHistoryActionRegistry']>
    readonly createHookEngine: UnwrapRef<typeof import('../../app/core/hooks/hooks')['createHookEngine']>
    readonly createLazyExtensionFactory: UnwrapRef<typeof import('../../app/composables/editor/useEditorExtensionLoader')['createLazyExtensionFactory']>
    readonly createLazyMarkFactory: UnwrapRef<typeof import('../../app/composables/editor/useEditorExtensionLoader')['createLazyMarkFactory']>
    readonly createLazyNodeFactory: UnwrapRef<typeof import('../../app/composables/editor/useEditorExtensionLoader')['createLazyNodeFactory']>
    readonly createRegistry: UnwrapRef<typeof import('../../app/composables/_registry')['createRegistry']>
    readonly createSidebarMultiPaneApi: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarEnvironment')['createSidebarMultiPaneApi']>
    readonly createTypedHookEngine: UnwrapRef<typeof import('../../app/core/hooks/typed-hooks')['createTypedHookEngine']>
    readonly createWorkspacePluginApi: UnwrapRef<typeof import('../../app/composables/plugins/workspace-runtime')['createWorkspacePluginApi']>
    readonly getDashboardPluginPage: UnwrapRef<typeof import('../../app/composables/dashboard/useDashboardPlugins')['getDashboardPluginPage']>
    readonly getPluginCapabilities: UnwrapRef<typeof import('../../app/composables/dashboard/useDashboardPlugins')['getPluginCapabilities']>
    readonly hasAllCapabilities: UnwrapRef<typeof import('../../app/composables/dashboard/useDashboardPlugins')['hasAllCapabilities']>
    readonly hasAnyCapability: UnwrapRef<typeof import('../../app/composables/dashboard/useDashboardPlugins')['hasAnyCapability']>
    readonly hasCapability: UnwrapRef<typeof import('../../app/composables/dashboard/useDashboardPlugins')['hasCapability']>
    readonly listDashboardPluginPages: UnwrapRef<typeof import('../../app/composables/dashboard/useDashboardPlugins')['listDashboardPluginPages']>
    readonly listEditorExtensions: UnwrapRef<typeof import('../../app/composables/editor/useEditorNodes')['listEditorExtensions']>
    readonly listEditorMarks: UnwrapRef<typeof import('../../app/composables/editor/useEditorNodes')['listEditorMarks']>
    readonly listEditorNodes: UnwrapRef<typeof import('../../app/composables/editor/useEditorNodes')['listEditorNodes']>
    readonly listRegisteredComposerActionIds: UnwrapRef<typeof import('../../app/composables/sidebar/useComposerActions')['listRegisteredComposerActionIds']>
    readonly listRegisteredDashboardPluginIds: UnwrapRef<typeof import('../../app/composables/dashboard/useDashboardPlugins')['listRegisteredDashboardPluginIds']>
    readonly listRegisteredDocumentHistoryActionIds: UnwrapRef<typeof import('../../app/composables/documents/useDocumentHistoryActions')['listRegisteredDocumentHistoryActionIds']>
    readonly listRegisteredEditorExtensionIds: UnwrapRef<typeof import('../../app/composables/editor/useEditorNodes')['listRegisteredEditorExtensionIds']>
    readonly listRegisteredEditorMarkIds: UnwrapRef<typeof import('../../app/composables/editor/useEditorNodes')['listRegisteredEditorMarkIds']>
    readonly listRegisteredEditorNodeIds: UnwrapRef<typeof import('../../app/composables/editor/useEditorNodes')['listRegisteredEditorNodeIds']>
    readonly listRegisteredEditorToolbarButtonIds: UnwrapRef<typeof import('../../app/composables/editor/useEditorToolbar')['listRegisteredEditorToolbarButtonIds']>
    readonly listRegisteredHeaderActionIds: UnwrapRef<typeof import('../../app/composables/sidebar/useHeaderActions')['listRegisteredHeaderActionIds']>
    readonly listRegisteredMessageActionIds: UnwrapRef<typeof import('../../app/composables/chat/useMessageActions')['listRegisteredMessageActionIds']>
    readonly listRegisteredProjectTreeActionIds: UnwrapRef<typeof import('../../app/composables/projects/useProjectTreeActions')['listRegisteredProjectTreeActionIds']>
    readonly listRegisteredSidebarFooterActionIds: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarSections')['listRegisteredSidebarFooterActionIds']>
    readonly listRegisteredSidebarSectionIds: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarSections')['listRegisteredSidebarSectionIds']>
    readonly listRegisteredThreadHistoryActionIds: UnwrapRef<typeof import('../../app/composables/threads/useThreadHistoryActions')['listRegisteredThreadHistoryActionIds']>
    readonly listWorkspacePluginInstances: UnwrapRef<typeof import('../../app/composables/plugins/workspace-runtime')['listWorkspacePluginInstances']>
    readonly loadAdminPlugins: UnwrapRef<typeof import('../../app/composables/admin/useAdminPlugins')['loadAdminPlugins']>
    readonly loadEditorExtensions: UnwrapRef<typeof import('../../app/composables/editor/useEditorExtensionLoader')['loadEditorExtensions']>
    readonly provideSidebarEnvironment: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarEnvironment')['provideSidebarEnvironment']>
    readonly provideSidebarPageControls: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarEnvironment')['provideSidebarPageControls']>
    readonly registerAdminPage: UnwrapRef<typeof import('../../app/composables/admin/useAdminPlugins')['registerAdminPage']>
    readonly registerAdminWidget: UnwrapRef<typeof import('../../app/composables/admin/useAdminPlugins')['registerAdminWidget']>
    readonly registerComposerAction: UnwrapRef<typeof import('../../app/composables/sidebar/useComposerActions')['registerComposerAction']>
    readonly registerDashboardPlugin: UnwrapRef<typeof import('../../app/composables/dashboard/useDashboardPlugins')['registerDashboardPlugin']>
    readonly registerDashboardPluginPage: UnwrapRef<typeof import('../../app/composables/dashboard/useDashboardPlugins')['registerDashboardPluginPage']>
    readonly registerDocumentHistoryAction: UnwrapRef<typeof import('../../app/composables/documents/useDocumentHistoryActions')['registerDocumentHistoryAction']>
    readonly registerEditorExtension: UnwrapRef<typeof import('../../app/composables/editor/useEditorNodes')['registerEditorExtension']>
    readonly registerEditorMark: UnwrapRef<typeof import('../../app/composables/editor/useEditorNodes')['registerEditorMark']>
    readonly registerEditorNode: UnwrapRef<typeof import('../../app/composables/editor/useEditorNodes')['registerEditorNode']>
    readonly registerEditorToolbarButton: UnwrapRef<typeof import('../../app/composables/editor/useEditorToolbar')['registerEditorToolbarButton']>
    readonly registerHeaderAction: UnwrapRef<typeof import('../../app/composables/sidebar/useHeaderActions')['registerHeaderAction']>
    readonly registerMessageAction: UnwrapRef<typeof import('../../app/composables/chat/useMessageActions')['registerMessageAction']>
    readonly registerProjectTreeAction: UnwrapRef<typeof import('../../app/composables/projects/useProjectTreeActions')['registerProjectTreeAction']>
    readonly registerSidebarFooterAction: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarSections')['registerSidebarFooterAction']>
    readonly registerSidebarPage: UnwrapRef<typeof import('../../app/composables/sidebar/registerSidebarPage')['default']>
    readonly registerSidebarPageWithPosts: UnwrapRef<typeof import('../../app/composables/sidebar/registerSidebarPage')['registerSidebarPageWithPosts']>
    readonly registerSidebarSection: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarSections')['registerSidebarSection']>
    readonly registerThreadHistoryAction: UnwrapRef<typeof import('../../app/composables/threads/useThreadHistoryActions')['registerThreadHistoryAction']>
    readonly registerWorkspacePluginInstance: UnwrapRef<typeof import('../../app/composables/plugins/workspace-runtime')['registerWorkspacePluginInstance']>
    readonly resolveAdminComponent: UnwrapRef<typeof import('../../app/composables/admin/useAdminPlugins')['resolveAdminComponent']>
    readonly resolveDashboardPluginPageComponent: UnwrapRef<typeof import('../../app/composables/dashboard/useDashboardPlugins')['resolveDashboardPluginPageComponent']>
    readonly state: UnwrapRef<typeof import('../../app/composables/admin/useAdminPlugins')['state']>
    readonly typedOn: UnwrapRef<typeof import('../../app/core/hooks/hook-keys')['typedOn']>
    readonly unregisterComposerAction: UnwrapRef<typeof import('../../app/composables/sidebar/useComposerActions')['unregisterComposerAction']>
    readonly unregisterDashboardPlugin: UnwrapRef<typeof import('../../app/composables/dashboard/useDashboardPlugins')['unregisterDashboardPlugin']>
    readonly unregisterDashboardPluginPage: UnwrapRef<typeof import('../../app/composables/dashboard/useDashboardPlugins')['unregisterDashboardPluginPage']>
    readonly unregisterDocumentHistoryAction: UnwrapRef<typeof import('../../app/composables/documents/useDocumentHistoryActions')['unregisterDocumentHistoryAction']>
    readonly unregisterEditorExtension: UnwrapRef<typeof import('../../app/composables/editor/useEditorNodes')['unregisterEditorExtension']>
    readonly unregisterEditorMark: UnwrapRef<typeof import('../../app/composables/editor/useEditorNodes')['unregisterEditorMark']>
    readonly unregisterEditorNode: UnwrapRef<typeof import('../../app/composables/editor/useEditorNodes')['unregisterEditorNode']>
    readonly unregisterEditorToolbarButton: UnwrapRef<typeof import('../../app/composables/editor/useEditorToolbar')['unregisterEditorToolbarButton']>
    readonly unregisterHeaderAction: UnwrapRef<typeof import('../../app/composables/sidebar/useHeaderActions')['unregisterHeaderAction']>
    readonly unregisterMessageAction: UnwrapRef<typeof import('../../app/composables/chat/useMessageActions')['unregisterMessageAction']>
    readonly unregisterProjectTreeAction: UnwrapRef<typeof import('../../app/composables/projects/useProjectTreeActions')['unregisterProjectTreeAction']>
    readonly unregisterSidebarFooterAction: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarSections')['unregisterSidebarFooterAction']>
    readonly unregisterSidebarSection: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarSections')['unregisterSidebarSection']>
    readonly unregisterThreadHistoryAction: UnwrapRef<typeof import('../../app/composables/threads/useThreadHistoryActions')['unregisterThreadHistoryAction']>
    readonly unregisterWorkspacePluginInstance: UnwrapRef<typeof import('../../app/composables/plugins/workspace-runtime')['unregisterWorkspacePluginInstance']>
    readonly useActiveDocumentIds: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarEnvironment')['useActiveDocumentIds']>
    readonly useActivePageId: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarPageControls')['useActivePageId']>
    readonly useActiveSections: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarEnvironment')['useActiveSections']>
    readonly useActiveThreadIds: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarEnvironment')['useActiveThreadIds']>
    readonly useAdminPages: UnwrapRef<typeof import('../../app/composables/admin/useAdminPlugins')['useAdminPages']>
    readonly useAdminWidgets: UnwrapRef<typeof import('../../app/composables/admin/useAdminPlugins')['useAdminWidgets']>
    readonly useComposerActions: UnwrapRef<typeof import('../../app/composables/sidebar/useComposerActions')['useComposerActions']>
    readonly useDashboardNavigation: UnwrapRef<typeof import('../../app/composables/dashboard/useDashboardPlugins')['useDashboardNavigation']>
    readonly useDashboardPluginPages: UnwrapRef<typeof import('../../app/composables/dashboard/useDashboardPlugins')['useDashboardPluginPages']>
    readonly useDashboardPlugins: UnwrapRef<typeof import('../../app/composables/dashboard/useDashboardPlugins')['useDashboardPlugins']>
    readonly useDocumentHistoryActions: UnwrapRef<typeof import('../../app/composables/documents/useDocumentHistoryActions')['useDocumentHistoryActions']>
    readonly useEditorToolbarButtons: UnwrapRef<typeof import('../../app/composables/editor/useEditorToolbar')['useEditorToolbarButtons']>
    readonly useExpandedProjects: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarEnvironment')['useExpandedProjects']>
    readonly useGlobalRegistry: UnwrapRef<typeof import('../../app/composables/_registry')['useGlobalRegistry']>
    readonly useHeaderActions: UnwrapRef<typeof import('../../app/composables/sidebar/useHeaderActions')['useHeaderActions']>
    readonly useHookEffect: UnwrapRef<typeof import('../../app/composables/core/useHookEffect')['useHookEffect']>
    readonly useHooks: UnwrapRef<typeof import('../../app/core/hooks/useHooks')['useHooks']>
    readonly useIsActivePage: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarPageControls')['useIsActivePage']>
    readonly useMessageActions: UnwrapRef<typeof import('../../app/composables/chat/useMessageActions')['useMessageActions']>
    readonly usePaneApps: UnwrapRef<typeof import('../../app/composables/core/usePaneApps')['usePaneApps']>
    readonly useProjectTreeActions: UnwrapRef<typeof import('../../app/composables/projects/useProjectTreeActions')['useProjectTreeActions']>
    readonly useResetToDefaultPage: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarPageControls')['useResetToDefaultPage']>
    readonly useSidebarDocuments: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarEnvironment')['useSidebarDocuments']>
    readonly useSidebarEnvironment: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarEnvironment')['useSidebarEnvironment']>
    readonly useSidebarFooterActions: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarSections')['useSidebarFooterActions']>
    readonly useSidebarMultiPane: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarEnvironment')['useSidebarMultiPane']>
    readonly useSidebarPageControls: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarPageControls')['useSidebarPageControls']>
    readonly useSidebarPageState: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarPageControls')['useSidebarPageState']>
    readonly useSidebarPages: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarPages')['useSidebarPages']>
    readonly useSidebarPostsApi: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarEnvironment')['useSidebarPostsApi']>
    readonly useSidebarProjects: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarEnvironment')['useSidebarProjects']>
    readonly useSidebarQuery: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarEnvironment')['useSidebarQuery']>
    readonly useSidebarSections: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarSections')['useSidebarSections']>
    readonly useSidebarThreads: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarEnvironment')['useSidebarThreads']>
    readonly useSwitchToPage: UnwrapRef<typeof import('../../app/composables/sidebar/useSidebarPageControls')['useSwitchToPage']>
    readonly useThreadHistoryActions: UnwrapRef<typeof import('../../app/composables/threads/useThreadHistoryActions')['useThreadHistoryActions']>
  const SidebarEnvironmentKey: typeof import('../../app/composables/sidebar/useSidebarEnvironment').SidebarEnvironmentKey
  const SidebarPageControlsKey: typeof import('../../app/composables/sidebar/useSidebarEnvironment').SidebarPageControlsKey
  const createAdminPluginApi: typeof import('../../app/composables/admin/useAdminPlugins').createAdminPluginApi
  const createHistoryActionRegistry: typeof import('../../app/composables/history/createHistoryActionRegistry').createHistoryActionRegistry
  const createHookEngine: typeof import('../../app/core/hooks/hooks').createHookEngine
  const createLazyExtensionFactory: typeof import('../../app/composables/editor/useEditorExtensionLoader').createLazyExtensionFactory
  const createLazyMarkFactory: typeof import('../../app/composables/editor/useEditorExtensionLoader').createLazyMarkFactory
  const createLazyNodeFactory: typeof import('../../app/composables/editor/useEditorExtensionLoader').createLazyNodeFactory
  const createRegistry: typeof import('../../app/composables/_registry').createRegistry
  const createSidebarMultiPaneApi: typeof import('../../app/composables/sidebar/useSidebarEnvironment').createSidebarMultiPaneApi
  const createTypedHookEngine: typeof import('../../app/core/hooks/typed-hooks').createTypedHookEngine
  const createWorkspacePluginApi: typeof import('../../app/composables/plugins/workspace-runtime').createWorkspacePluginApi
  const getDashboardPluginPage: typeof import('../../app/composables/dashboard/useDashboardPlugins').getDashboardPluginPage
  const getPluginCapabilities: typeof import('../../app/composables/dashboard/useDashboardPlugins').getPluginCapabilities
  const hasAllCapabilities: typeof import('../../app/composables/dashboard/useDashboardPlugins').hasAllCapabilities
  const hasAnyCapability: typeof import('../../app/composables/dashboard/useDashboardPlugins').hasAnyCapability
  const hasCapability: typeof import('../../app/composables/dashboard/useDashboardPlugins').hasCapability
  const listDashboardPluginPages: typeof import('../../app/composables/dashboard/useDashboardPlugins').listDashboardPluginPages
  const listEditorExtensions: typeof import('../../app/composables/editor/useEditorNodes').listEditorExtensions
  const listEditorMarks: typeof import('../../app/composables/editor/useEditorNodes').listEditorMarks
  const listEditorNodes: typeof import('../../app/composables/editor/useEditorNodes').listEditorNodes
  const listRegisteredComposerActionIds: typeof import('../../app/composables/sidebar/useComposerActions').listRegisteredComposerActionIds
  const listRegisteredDashboardPluginIds: typeof import('../../app/composables/dashboard/useDashboardPlugins').listRegisteredDashboardPluginIds
  const listRegisteredDocumentHistoryActionIds: typeof import('../../app/composables/documents/useDocumentHistoryActions').listRegisteredDocumentHistoryActionIds
  const listRegisteredEditorExtensionIds: typeof import('../../app/composables/editor/useEditorNodes').listRegisteredEditorExtensionIds
  const listRegisteredEditorMarkIds: typeof import('../../app/composables/editor/useEditorNodes').listRegisteredEditorMarkIds
  const listRegisteredEditorNodeIds: typeof import('../../app/composables/editor/useEditorNodes').listRegisteredEditorNodeIds
  const listRegisteredEditorToolbarButtonIds: typeof import('../../app/composables/editor/useEditorToolbar').listRegisteredEditorToolbarButtonIds
  const listRegisteredHeaderActionIds: typeof import('../../app/composables/sidebar/useHeaderActions').listRegisteredHeaderActionIds
  const listRegisteredMessageActionIds: typeof import('../../app/composables/chat/useMessageActions').listRegisteredMessageActionIds
  const listRegisteredProjectTreeActionIds: typeof import('../../app/composables/projects/useProjectTreeActions').listRegisteredProjectTreeActionIds
  const listRegisteredSidebarFooterActionIds: typeof import('../../app/composables/sidebar/useSidebarSections').listRegisteredSidebarFooterActionIds
  const listRegisteredSidebarSectionIds: typeof import('../../app/composables/sidebar/useSidebarSections').listRegisteredSidebarSectionIds
  const listRegisteredThreadHistoryActionIds: typeof import('../../app/composables/threads/useThreadHistoryActions').listRegisteredThreadHistoryActionIds
  const listWorkspacePluginInstances: typeof import('../../app/composables/plugins/workspace-runtime').listWorkspacePluginInstances
  const loadAdminPlugins: typeof import('../../app/composables/admin/useAdminPlugins').loadAdminPlugins
  const loadEditorExtensions: typeof import('../../app/composables/editor/useEditorExtensionLoader').loadEditorExtensions
  const provideSidebarEnvironment: typeof import('../../app/composables/sidebar/useSidebarEnvironment').provideSidebarEnvironment
  const provideSidebarPageControls: typeof import('../../app/composables/sidebar/useSidebarEnvironment').provideSidebarPageControls
  const registerAdminPage: typeof import('../../app/composables/admin/useAdminPlugins').registerAdminPage
  const registerAdminWidget: typeof import('../../app/composables/admin/useAdminPlugins').registerAdminWidget
  const registerComposerAction: typeof import('../../app/composables/sidebar/useComposerActions').registerComposerAction
  const registerDashboardPlugin: typeof import('../../app/composables/dashboard/useDashboardPlugins').registerDashboardPlugin
  const registerDashboardPluginPage: typeof import('../../app/composables/dashboard/useDashboardPlugins').registerDashboardPluginPage
  const registerDocumentHistoryAction: typeof import('../../app/composables/documents/useDocumentHistoryActions').registerDocumentHistoryAction
  const registerEditorExtension: typeof import('../../app/composables/editor/useEditorNodes').registerEditorExtension
  const registerEditorMark: typeof import('../../app/composables/editor/useEditorNodes').registerEditorMark
  const registerEditorNode: typeof import('../../app/composables/editor/useEditorNodes').registerEditorNode
  const registerEditorToolbarButton: typeof import('../../app/composables/editor/useEditorToolbar').registerEditorToolbarButton
  const registerHeaderAction: typeof import('../../app/composables/sidebar/useHeaderActions').registerHeaderAction
  const registerMessageAction: typeof import('../../app/composables/chat/useMessageActions').registerMessageAction
  const registerProjectTreeAction: typeof import('../../app/composables/projects/useProjectTreeActions').registerProjectTreeAction
  const registerSidebarFooterAction: typeof import('../../app/composables/sidebar/useSidebarSections').registerSidebarFooterAction
  const registerSidebarPage: typeof import('../../app/composables/sidebar/registerSidebarPage').default
  const registerSidebarPageWithPosts: typeof import('../../app/composables/sidebar/registerSidebarPage').registerSidebarPageWithPosts
  const registerSidebarSection: typeof import('../../app/composables/sidebar/useSidebarSections').registerSidebarSection
  const registerThreadHistoryAction: typeof import('../../app/composables/threads/useThreadHistoryActions').registerThreadHistoryAction
  const registerWorkspacePluginInstance: typeof import('../../app/composables/plugins/workspace-runtime').registerWorkspacePluginInstance
  const resolveAdminComponent: typeof import('../../app/composables/admin/useAdminPlugins').resolveAdminComponent
  const resolveDashboardPluginPageComponent: typeof import('../../app/composables/dashboard/useDashboardPlugins').resolveDashboardPluginPageComponent
  const state: typeof import('../../app/composables/admin/useAdminPlugins').state
  const typedOn: typeof import('../../app/core/hooks/hook-keys').typedOn
  const unregisterComposerAction: typeof import('../../app/composables/sidebar/useComposerActions').unregisterComposerAction
  const unregisterDashboardPlugin: typeof import('../../app/composables/dashboard/useDashboardPlugins').unregisterDashboardPlugin
  const unregisterDashboardPluginPage: typeof import('../../app/composables/dashboard/useDashboardPlugins').unregisterDashboardPluginPage
  const unregisterDocumentHistoryAction: typeof import('../../app/composables/documents/useDocumentHistoryActions').unregisterDocumentHistoryAction
  const unregisterEditorExtension: typeof import('../../app/composables/editor/useEditorNodes').unregisterEditorExtension
  const unregisterEditorMark: typeof import('../../app/composables/editor/useEditorNodes').unregisterEditorMark
  const unregisterEditorNode: typeof import('../../app/composables/editor/useEditorNodes').unregisterEditorNode
  const unregisterEditorToolbarButton: typeof import('../../app/composables/editor/useEditorToolbar').unregisterEditorToolbarButton
  const unregisterHeaderAction: typeof import('../../app/composables/sidebar/useHeaderActions').unregisterHeaderAction
  const unregisterMessageAction: typeof import('../../app/composables/chat/useMessageActions').unregisterMessageAction
  const unregisterProjectTreeAction: typeof import('../../app/composables/projects/useProjectTreeActions').unregisterProjectTreeAction
  const unregisterSidebarFooterAction: typeof import('../../app/composables/sidebar/useSidebarSections').unregisterSidebarFooterAction
  const unregisterSidebarSection: typeof import('../../app/composables/sidebar/useSidebarSections').unregisterSidebarSection
  const unregisterThreadHistoryAction: typeof import('../../app/composables/threads/useThreadHistoryActions').unregisterThreadHistoryAction
  const unregisterWorkspacePluginInstance: typeof import('../../app/composables/plugins/workspace-runtime').unregisterWorkspacePluginInstance
  const useActiveDocumentIds: typeof import('../../app/composables/sidebar/useSidebarEnvironment').useActiveDocumentIds
  const useActivePageId: typeof import('../../app/composables/sidebar/useSidebarPageControls').useActivePageId
  const useActiveSections: typeof import('../../app/composables/sidebar/useSidebarEnvironment').useActiveSections
  const useActiveThreadIds: typeof import('../../app/composables/sidebar/useSidebarEnvironment').useActiveThreadIds
  const useAdminPages: typeof import('../../app/composables/admin/useAdminPlugins').useAdminPages
  const useAdminWidgets: typeof import('../../app/composables/admin/useAdminPlugins').useAdminWidgets
  const useComposerActions: typeof import('../../app/composables/sidebar/useComposerActions').useComposerActions
  const useDashboardNavigation: typeof import('../../app/composables/dashboard/useDashboardPlugins').useDashboardNavigation
  const useDashboardPluginPages: typeof import('../../app/composables/dashboard/useDashboardPlugins').useDashboardPluginPages
  const useDashboardPlugins: typeof import('../../app/composables/dashboard/useDashboardPlugins').useDashboardPlugins
  const useDocumentHistoryActions: typeof import('../../app/composables/documents/useDocumentHistoryActions').useDocumentHistoryActions
  const useEditorToolbarButtons: typeof import('../../app/composables/editor/useEditorToolbar').useEditorToolbarButtons
  const useExpandedProjects: typeof import('../../app/composables/sidebar/useSidebarEnvironment').useExpandedProjects
  const useGlobalRegistry: typeof import('../../app/composables/_registry').useGlobalRegistry
  const useHeaderActions: typeof import('../../app/composables/sidebar/useHeaderActions').useHeaderActions
  const useHookEffect: typeof import('../../app/composables/core/useHookEffect').useHookEffect
  const useHooks: typeof import('../../app/core/hooks/useHooks').useHooks
  const useIsActivePage: typeof import('../../app/composables/sidebar/useSidebarPageControls').useIsActivePage
  const useMessageActions: typeof import('../../app/composables/chat/useMessageActions').useMessageActions
  const usePaneApps: typeof import('../../app/composables/core/usePaneApps').usePaneApps
  const useProjectTreeActions: typeof import('../../app/composables/projects/useProjectTreeActions').useProjectTreeActions
  const useResetToDefaultPage: typeof import('../../app/composables/sidebar/useSidebarPageControls').useResetToDefaultPage
  const useSidebarDocuments: typeof import('../../app/composables/sidebar/useSidebarEnvironment').useSidebarDocuments
  const useSidebarEnvironment: typeof import('../../app/composables/sidebar/useSidebarEnvironment').useSidebarEnvironment
  const useSidebarFooterActions: typeof import('../../app/composables/sidebar/useSidebarSections').useSidebarFooterActions
  const useSidebarMultiPane: typeof import('../../app/composables/sidebar/useSidebarEnvironment').useSidebarMultiPane
  const useSidebarPageControls: typeof import('../../app/composables/sidebar/useSidebarPageControls').useSidebarPageControls
  const useSidebarPageState: typeof import('../../app/composables/sidebar/useSidebarPageControls').useSidebarPageState
  const useSidebarPages: typeof import('../../app/composables/sidebar/useSidebarPages').useSidebarPages
  const useSidebarPostsApi: typeof import('../../app/composables/sidebar/useSidebarEnvironment').useSidebarPostsApi
  const useSidebarProjects: typeof import('../../app/composables/sidebar/useSidebarEnvironment').useSidebarProjects
  const useSidebarQuery: typeof import('../../app/composables/sidebar/useSidebarEnvironment').useSidebarQuery
  const useSidebarSections: typeof import('../../app/composables/sidebar/useSidebarSections').useSidebarSections
  const useSidebarThreads: typeof import('../../app/composables/sidebar/useSidebarEnvironment').useSidebarThreads
  const useSwitchToPage: typeof import('../../app/composables/sidebar/useSidebarPageControls').useSwitchToPage
  const useThreadHistoryActions: typeof import('../../app/composables/threads/useThreadHistoryActions').useThreadHistoryActions
  export type { AdminPageDef, AdminWidgetDef, AdminComponent, AdminPlugin, AdminPluginApi } from '../../app/composables/admin/useAdminPlugins'
  export type { ChatMessageAction } from '../../app/composables/chat/useMessageActions'
  export type { ComposerActionContext, ComposerAction, ComposerActionEntry } from '../../app/composables/sidebar/useComposerActions'
  export type { DashboardPlugin, DashboardPluginPage, DashboardNavigationErrorCode, DashboardNavigationError, DashboardNavigationState, DashboardNavigationResult, UseDashboardNavigationOptions } from '../../app/composables/dashboard/useDashboardPlugins'
  export type { DocumentHistoryAction } from '../../app/composables/documents/useDocumentHistoryActions'
  export type { EditorInstance, OpenRouterMessage, AiSendBeforePayload, AiSendAfterPayloadTimings, AiSendAfterPayload, AiStreamDeltaContext, AiStreamReasoningContext, AiStreamCompleteContext, AiStreamErrorContext, AiStreamDeltaPayload, AiStreamReasoningPayload, AiStreamCompletePayload, AiStreamErrorPayload, AiRetryBeforePayload, AiRetryAfterPayload, UiPaneMsgBase, UiPaneMsgReceived, UiPaneActivePayload, UiPaneBlurPayload, UiPaneSwitchPayload, UiPaneThreadChangedPayload, UiPaneDocChangedPayload, UiPaneMsgSentPayload, UiPaneMsgReceivedPayload, UiSidebarSelectPayload, UiChatNewPayload, AppInitPayload, FilesAttachPayload, FilesAttachInputPayload, BranchMode, BranchForkOptions, RetryBranchParams, BranchForkBeforePayload, BranchContextAfterPayload, KvUpsertByNameInput, MessageEntity, MessageCreateEntity, ThreadEntity, ThreadCreateEntity, DocumentEntity, FileEntity, ProjectEntity, PostEntity, PostCreateEntity, PromptEntity, AttachmentEntity, KvEntry, Permission, WorkspaceRole, AccessDecision, SessionContext, SyncScopePayload, SyncPendingOpPayload, NotificationAction, NotificationCreatePayload, NotificationEntity, StorageFileUploadBeforePayload, StorageFileUploadAfterPayload, StorageFileDownloadBeforePayload, StorageFileDownloadAfterPayload, StorageFileUrlOptionsPayload, StorageFileUploadPolicyPayload, StorageFileGcPayload, DbCreatePayload, DbUpdatePayload, DbDeletePayload, DbEntityName, DbOperation, DbPhase, DbDeleteType, DbActionHookName, DbFilterHookName, CoreActionHookName, ExtensionActionHookName, ActionHookName, CoreFilterHookName, ExtensionFilterHookName, FilterHookName, HookName, CoreHookPayloadMap, HookPayloadMap, InferHookParams, InferHookReturn, InferHookCallback, IsAction, IsFilter, ExtractHookPayload, MatchingHooks, InferDbEntity, InferDbCreateEntity, Tail, SuggestSimilar, ValidateHookName, TypeName, CallbackMismatch } from '../../app/core/hooks/hook-types'
  export type { EditorNode, EditorMark, EditorExtension } from '../../app/composables/editor/useEditorNodes'
  export type { EditorToolbarButton } from '../../app/composables/editor/useEditorToolbar'
  export type { HeaderActionContext, HeaderAction, HeaderActionEntry } from '../../app/composables/sidebar/useHeaderActions'
  export type { HistoryActionRegistryItem } from '../../app/composables/history/createHistoryActionRegistry'
  export type { HookFn, HookEngine, HookKind, OnOptions, RegisterOptions } from '../../app/core/hooks/hooks'
  export type { KnownHookKey, DbFamily, DbHookKey, HookKey, ChatOutgoingFilterReturn, ChatIncomingFilterReturn, FilesAttachFilterReturn } from '../../app/core/hooks/hook-keys'
  export type { LazyEditorNodeFactory, LazyEditorMarkFactory, LazyEditorExtensionFactory, EditorNodeDescriptor, EditorMarkDescriptor, EditorExtensionDescriptor, LoadedExtensions } from '../../app/composables/editor/useEditorExtensionLoader'
  export type { PaneAppDef, RegisteredPaneApp } from '../../app/composables/core/usePaneApps'
  export type { ProjectTreeKind, ShowOnKind, ProjectTreeChild, ProjectTreeRoot, ProjectTreeRow, ProjectTreeHandlerCtx, ProjectTreeAction } from '../../app/composables/projects/useProjectTreeActions'
  export type { RegisterSidebarPageOptions, RegisterSidebarPageWithPostsOptions } from '../../app/composables/sidebar/registerSidebarPage'
  export type { RegistryItem, RegistryApi, RegistrationHandle } from '../../app/composables/_registry'
  export type { SidebarPageControls, SidebarMultiPaneApi, SidebarEnvironment } from '../../app/composables/sidebar/useSidebarEnvironment'
  export type { SidebarPageDef, SidebarPageContext, SidebarActivateContext, RegisteredSidebarPage } from '../../app/composables/sidebar/useSidebarPages'
  export type { SidebarSectionPlacement, SidebarSection, SidebarSectionGroups, SidebarFooterActionContext, ChromeActionColor, SidebarFooterAction, SidebarFooterActionEntry } from '../../app/composables/sidebar/useSidebarSections'
  export type { ThreadHistoryAction } from '../../app/composables/threads/useThreadHistoryActions'
  export type { TypedHookEngine } from '../../app/core/hooks/typed-hooks'
  export type { WorkspacePluginSource, Or3WorkspacePluginApi, Or3WorkspacePlugin } from '../../app/composables/plugins/workspace-runtime'
  import('../../app/composables/_registry')
  import('../../app/composables/admin/useAdminPlugins')
  import('../../app/composables/chat/useMessageActions')
  import('../../app/composables/core/usePaneApps')
  import('../../app/composables/dashboard/useDashboardPlugins')
  import('../../app/composables/documents/useDocumentHistoryActions')
  import('../../app/composables/editor/useEditorExtensionLoader')
  import('../../app/composables/editor/useEditorNodes')
  import('../../app/composables/editor/useEditorToolbar')
  import('../../app/composables/history/createHistoryActionRegistry')
  import('../../app/composables/plugins/workspace-runtime')
  import('../../app/composables/projects/useProjectTreeActions')
  import('../../app/composables/sidebar/registerSidebarPage')
  import('../../app/composables/sidebar/useComposerActions')
  import('../../app/composables/sidebar/useHeaderActions')
  import('../../app/composables/sidebar/useSidebarEnvironment')
  import('../../app/composables/sidebar/useSidebarPages')
  import('../../app/composables/sidebar/useSidebarSections')
  import('../../app/composables/threads/useThreadHistoryActions')
  import('../../app/core/hooks/hook-keys')
  import('../../app/core/hooks/hook-types')
  import('../../app/core/hooks/hooks')
  import('../../app/core/hooks/typed-hooks')
