/**
 * Shared fixtures for the acquisition tests: a genuine portable-profile package
 * (isolated-client, browser-only, generated by the SDK's own profile authoring),
 * a fake registry that speaks the marketplace's real catalog/trust contract, and
 * the Ed25519 helpers used to sign releases and advisories.
 *
 * The fixture is deliberately *not* a trusted-host server package wearing a
 * portable label: the profile validator, the loader preflight and the authority
 * digest are all checked against real profile output.
 */

import { createHash } from 'node:crypto';
import { mkdirSync, mkdtempSync, writeFileSync } from 'node:fs';
import { promises as fs } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
    applyPortableProfileToManifest,
    defineOr3PortableProfile,
    type Or3PortableProfile,
} from '@or3/plugin-sdk/profile';
import { writeDeterministicPackageZip } from '@or3/plugin-sdk/package-archive';
import { verifyPackageTree } from '../../../../admin/plugins/package-tree';
import {
    encodeRegistryAdvisorySnapshot,
    type AdvisoryDocument,
    type RegistryAdvisoryCheckpoint,
    type RegistryAdvisorySnapshot,
    type ReleaseMetadataDocument,
} from '~~/shared/plugins/acquisition/release-metadata';
import { sha256Identity } from '~~/shared/plugins/digest';
import { signRegistryAdvisoryCheckpointForTest, signReleaseMetadataForTest } from '../release-verify';
import type { MarketplaceReleaseKey } from '../config';

export const ORIGIN = 'https://market.example';
export const PORTABLE_PROFILE = 'or3-portable-client-v1';

const roots: string[] = [];

export function tempRoot(prefix = 'or3-acquisition-'): string {
    const root = mkdtempSync(join(tmpdir(), prefix));
    roots.push(root);
    return root;
}

/** The immutable store chmods package trees read-only; undo that before cleanup. */
export async function cleanupRoots(): Promise<void> {
    for (const root of roots.splice(0)) await forceRemove(root);
}

async function forceRemove(root: string): Promise<void> {
    const entries = await fs.readdir(root, { withFileTypes: true }).catch(() => []);
    for (const entry of entries) {
        const target = join(root, entry.name);
        if (entry.isDirectory()) await forceRemove(target);
        else await fs.chmod(target, 0o644).catch(() => undefined);
    }
    await fs.chmod(root, 0o755).catch(() => undefined);
    await fs.rm(root, { recursive: true, force: true }).catch(() => undefined);
}

export interface TestKey {
    readonly key: MarketplaceReleaseKey;
    readonly privateKeyBase64: string;
}

export async function makeKey(keyId = 'or3-release'): Promise<TestKey> {
    const pair = (await crypto.subtle.generateKey({ name: 'Ed25519' }, true, [
        'sign',
        'verify',
    ])) as CryptoKeyPair;
    const pkcs8 = new Uint8Array(await crypto.subtle.exportKey('pkcs8', pair.privateKey));
    const publicJwk = await crypto.subtle.exportKey('jwk', pair.publicKey);
    let binary = '';
    for (const byte of pkcs8) binary += String.fromCharCode(byte);
    return {
        key: {
            keyId,
            publicJwk: { kty: 'OKP', crv: 'Ed25519', x: publicJwk.x as string },
        },
        privateKeyBase64: btoa(binary),
    };
}

/** The portable profile a fixture package is authored against. */
export function portableProfile(input: { requiredField?: boolean } = {}): Or3PortableProfile {
    return defineOr3PortableProfile({
        profile: PORTABLE_PROFILE,
        destinations: [
            {
                id: 'api.read',
                methods: ['GET'],
                hosts: ['api.example'],
                scopes: ['read'],
            },
        ],
        connections: [],
        dataScopes: [],
        writes: [],
        features: [],
        settingsSchemaPath: 'or3.settings.schema.json',
        fields: [
            {
                key: 'token',
                label: 'Token',
                kind: 'text',
                required: input.requiredField ?? false,
                order: 1,
            },
        ],
        firstAction: { operationId: 'api.read', label: 'Read', usesSampleContext: false },
    });
}

export function portableManifest(
    version: string,
    profile: Or3PortableProfile,
    stateReads = { minimum: 1, maximum: 1 }
): Record<string, unknown> {
    return {
        ...applyPortableProfileToManifest(
            {
                manifestVersion: 2,
                kind: 'plugin',
                id: 'alpha',
                name: 'Alpha',
                version,
                capabilities: [],
                engines: { or3: '^0.3.0', pluginApi: '^2.0.0' },
                runtime: {
                    client: { entry: 'client.mjs', format: 'esm', isolation: 'worker' },
                },
                requestedGrants: ['network.http'],
                features: { required: [], optional: [] },
                dependencies: { required: [], optional: [] },
                trust: 'isolated-client',
                settings: { version: 1 },
                stateCompatibility: { version: 1, reads: stateReads, rollback: 'safe' },
            } as never,
            profile
        ),
    };
}

export function portablePackageTree(input: {
    version: string;
    requiredField?: boolean;
    stateReads?: { minimum: number; maximum: number };
    /** Manifest to write instead of the conformant one, for refusal tests. */
    disguisedTrustedHost?: boolean;
}): { root: string; profile: Or3PortableProfile } {
    const profile = portableProfile({ requiredField: input.requiredField });
    const root = tempRoot('or3-package-');
    mkdirSync(root, { recursive: true });
    const manifest = input.disguisedTrustedHost
        ? {
              ...portableManifest(input.version, profile, input.stateReads),
              trust: 'trusted-host',
              runtime: {
                  server: {
                      routes: [
                          { method: 'GET', path: 'health', handler: 'server/health.get.mjs' },
                      ],
                  },
              },
          }
        : portableManifest(input.version, profile, input.stateReads);
    writeFileSync(join(root, 'or3.manifest.json'), JSON.stringify(manifest));
    for (const [name, contents] of Object.entries(profile.files)) {
        writeFileSync(join(root, name), contents);
    }
    writeFileSync(
        join(root, 'or3.settings.schema.json'),
        JSON.stringify({ type: 'object', properties: { token: { type: 'string' } } })
    );
    writeFileSync(join(root, 'client.mjs'), 'export default async () => true;\n');
    writeFileSync(join(root, 'package.json'), JSON.stringify({ name: 'alpha', type: 'module' }));
    return { root, profile };
}

export interface RegistryArtifactFixture {
    readonly bytes: Uint8Array;
    readonly signed: ReleaseMetadataDocument;
    readonly treeDigest: `sha256-${string}`;
    readonly key: MarketplaceReleaseKey;
    readonly privateKeyBase64: string;
    readonly releaseId: string;
}

export interface ReleaseFixture extends RegistryArtifactFixture {
    readonly profile: Or3PortableProfile;
    readonly version: string;
    /** The extracted package tree, for tests that install or inspect it. */
    readonly treePath: string;
}

export async function releaseFixture(input: {
    version: string;
    releaseId?: string;
    pluginId?: string;
    requiredField?: boolean;
    stateReads?: { minimum: number; maximum: number };
    authoritySha256?: `sha256-${string}`;
    profile?: string;
    disguisedTrustedHost?: boolean;
}): Promise<ReleaseFixture> {
    const key = await makeKey();
    const { root, profile } = portablePackageTree(input);
    const verification = await verifyPackageTree(root);
    const bytes = await writeDeterministicPackageZip(root);
    const archiveSha256 = `sha256-${createHash('sha256').update(bytes).digest('hex')}`;
    const document: ReleaseMetadataDocument = {
        schemaVersion: 1,
        releaseId: input.releaseId ?? `rel_${input.version}`,
        pluginId: input.pluginId ?? 'alpha',
        publisherNamespace: 'acme',
        version: input.version,
        archiveSha256: archiveSha256 as `sha256-${string}`,
        packageTreeSha256: verification.digest,
        manifestSha256: verification.manifestDigest,
        // The signed authority digest is the profile's own canonical policy
        // revision: the same rule the authoring SDK (and reviewer) uses.
        authoritySha256: input.authoritySha256 ?? profile.revisions.policy,
        sourceSha256: `sha256-${'e'.repeat(64)}` as `sha256-${string}`,
        profile: input.profile ?? PORTABLE_PROFILE,
        engines: { or3: '>=0.3.0', pluginApi: '>=2.0.0' },
        features: [],
        requestedGrants: [],
        reviewId: 'rev_1',
        license: 'MIT',
        publishedAt: new Date(Date.now() - 60_000).toISOString(),
    };
    const signed = await signReleaseMetadataForTest({
        document,
        keyId: key.key.keyId,
        privateKeyBase64: key.privateKeyBase64,
    });
    return {
        bytes,
        signed,
        treeDigest: verification.digest,
        key: key.key,
        privateKeyBase64: key.privateKeyBase64,
        profile,
        version: input.version,
        releaseId: document.releaseId,
        treePath: root,
    };
}

export function jsonResponse(body: unknown, status = 200): Response {
    return new Response(JSON.stringify(body), {
        status,
        headers: { 'content-type': 'application/json' },
    });
}

export interface FakeRegistryOptions {
    readonly fixture: RegistryArtifactFixture;
    readonly advisories?: readonly (AdvisoryDocument & { signature?: unknown })[];
    /** Transports for advisory documents, keyed by sequence. */
    readonly advisoryDocuments?: Readonly<Record<number, unknown>>;
    readonly failDownload?: () => boolean;
    /** Answer 200 to a Range request instead of 206 (ignored range). */
    readonly ignoreRange?: boolean;
    readonly onRequest?: (url: string) => void;
    /**
     * Model a paid release: the public artifact path refuses with
     * `coverage-required`, and only the token-authenticated Library route serves
     * the bytes.
     */
    readonly coverageRequired?: boolean;
    /** Override the complete-checkpoint sequence for cursor replay tests. */
    readonly checkpointSequence?: number;
    /** Full snapshot override, for revision/equivocation replay tests. */
    readonly snapshot?: RegistryAdvisorySnapshot;
    readonly keyStatuses?: RegistryAdvisorySnapshot['keyStatuses'];
    /** Override individual checkpoint envelope fields. */
    readonly checkpoint?: Partial<
        Pick<
            RegistryAdvisoryCheckpoint,
            'registryOrigin' | 'revision' | 'sequence' | 'issuedAt' | 'expiresAt' | 'snapshotSha256'
        >
    >;
    /** Sign the checkpoint with a different key than the release fixture. */
    readonly checkpointKey?: TestKey;
    /** Replace the whole `/checkpoint` response, for malformed-shape tests. */
    readonly checkpointResponse?: unknown;
}

/**
 * A transport that answers the marketplace's real public trust endpoints:
 * the release metadata wrapper, the advisory log, the advisory documents and the
 * content-addressed artifact. With `coverageRequired` it also models the
 * linked-host artifact route.
 */
export function fakeRegistryTransport(options: FakeRegistryOptions): typeof fetch {
    const { fixture } = options;
    const snapshotPromise = (async (): Promise<RegistryAdvisorySnapshot> => {
        if (options.snapshot) return options.snapshot;
        const advisories = [...(options.advisories ?? [])] as AdvisoryDocument[];
        const sequence = options.checkpointSequence ?? Math.max(9, ...advisories.map((entry) => entry.sequence));
        return {
            schemaVersion: 2,
            // Every mutation bumps the revision in the real registry; fixtures
            // only need it to be monotonic across replayed responses.
            revision: 1,
            sequence,
            advisories,
            keyStatuses: options.keyStatuses ?? [
                {
                    keyId: fixture.key.keyId,
                    status: 'active',
                    effectiveAt: new Date(Date.now() - 60_000).toISOString(),
                },
            ],
        };
    })();
    const checkpointPromise = snapshotPromise.then(async (snapshot) => {
        const signer = options.checkpointKey ?? {
            key: fixture.key,
            privateKeyBase64: fixture.privateKeyBase64,
        };
        const issuedAt = options.checkpoint?.issuedAt ?? new Date().toISOString();
        const expiresAt = options.checkpoint?.expiresAt ?? new Date(Date.now() + 10 * 60_000).toISOString();
        const unsigned: RegistryAdvisoryCheckpoint = {
            schemaVersion: 2,
            registryOrigin: options.checkpoint?.registryOrigin ?? ORIGIN,
            revision: options.checkpoint?.revision ?? snapshot.revision,
            sequence: options.checkpoint?.sequence ?? snapshot.sequence,
            issuedAt,
            expiresAt,
            snapshotSha256:
                options.checkpoint?.snapshotSha256 ??
                (await sha256Identity(encodeRegistryAdvisorySnapshot(snapshot))),
            signature: { keyId: signer.key.keyId, algorithm: 'ed25519', value: 'fixture' },
        };
        return await signRegistryAdvisoryCheckpointForTest({
            checkpoint: unsigned,
            keyId: signer.key.keyId,
            privateKeyBase64: signer.privateKeyBase64,
        });
    });
    const artifactResponse = (range: string | undefined): Response => {
        if (range && !options.ignoreRange) {
            const from = Number(range.replace(/bytes=/, '').replace(/-.*/, ''));
            const partial = fixture.bytes.slice(from);
            return new Response(new Uint8Array(partial), {
                status: 206,
                headers: { 'content-length': String(partial.byteLength) },
            });
        }
        return new Response(new Uint8Array(fixture.bytes), {
            status: 200,
            headers: { 'content-length': String(fixture.bytes.byteLength) },
        });
    };
    return (async (input: RequestInfo | URL, init?: RequestInit) => {
        const url = String(input);
        options.onRequest?.(url);
        if (/\/releases\/[^/]+\/[^/]+\/metadata$/.test(url)) {
            return jsonResponse({
                releaseId: fixture.releaseId,
                document: fixture.signed,
            });
        }
        if (url.endsWith('/checkpoint')) {
            if (options.checkpointResponse !== undefined) {
                return jsonResponse(options.checkpointResponse);
            }
            const [checkpoint, snapshot] = await Promise.all([checkpointPromise, snapshotPromise]);
            return jsonResponse({ checkpoint, snapshot });
        }
        if (url.endsWith('/advisories')) {
            return jsonResponse({
                advisories: (options.advisories ?? []).map((advisory) => ({
                    sequence: advisory.sequence,
                    kind: advisory.kind,
                    releaseId: advisory.releaseId,
                    pluginId: advisory.pluginId,
                    version: advisory.version,
                    archiveSha256: advisory.archiveSha256,
                    reason: advisory.reason,
                    issuedAt: advisory.issuedAt,
                    keyId: advisory.signature ? (advisory.signature as { keyId: string }).keyId : null,
                })),
            });
        }
        const advisoryMatch = url.match(/\/advisories\/(\d+)$/);
        if (advisoryMatch) {
            const sequence = Number(advisoryMatch[1]);
            const document =
                options.advisoryDocuments?.[sequence] ??
                (options.advisories ?? []).find((advisory) => advisory.sequence === sequence);
            if (!document) return new Response('missing', { status: 404 });
            return jsonResponse({ sequence, document });
        }
        const headers = (init?.headers as Record<string, string> | undefined) ?? {};
        if (url.includes('/api/v1/library/releases/')) {
            if (options.coverageRequired && !headers['x-or3-library-token']) {
                return jsonResponse(
                    {
                        statusCode: 403,
                        statusMessage: 'acquisition-required',
                        data: { code: 'acquisition-required' },
                    },
                    403
                );
            }
            return artifactResponse(headers.range);
        }
        if (url.includes('/artifacts/')) {
            if (options.coverageRequired) {
                return jsonResponse(
                    {
                        statusCode: 403,
                        statusMessage: 'coverage-required',
                        data: { code: 'coverage-required' },
                    },
                    403
                );
            }
            if (options.failDownload?.()) throw new Error('connection reset');
            return artifactResponse(headers.range);
        }
        return new Response('missing', { status: 404 });
    }) as typeof fetch;
}
