<script setup lang="ts">
/**
 * User-facing setup page for an installed portable plugin.
 *
 * Everything on this page is host-generated from the package descriptors and the
 * workspace's stored connections: the plugin supplies data, the host renders and
 * mediates every action.
 */
import PluginSetupPanel from '~/components/plugins/PluginSetupPanel.vue';
import type { SetupPlan } from '~~/shared/plugins/setup/plan';

type SetupPlanResponse = {
    plan: SetupPlan | null;
    status: { status: string; label: string; nextAction?: string; blocked?: boolean };
    firstAction: {
        operationId: string;
        label: string;
        contextKind: 'selected' | 'sample';
        ready: boolean;
        reason?: string;
    };
    problems: readonly string[];
    destinations: readonly {
        id: string;
        hosts: readonly string[];
        methods: readonly string[];
        scopes: readonly string[];
    }[];
    durableConnections: boolean;
};

const route = useRoute();
const pluginId = computed(() => String(route.params.pluginId ?? ''));

const { data, error, refresh } = await useFetch<SetupPlanResponse>(
    () => `/api/plugins/${encodeURIComponent(pluginId.value)}/setup-plan`,
    { key: () => `plugin-setup-${pluginId.value}` }
);

const busy = ref(false);
const message = ref<string | null>(null);

async function saveSettings(values: Record<string, string | number | boolean>): Promise<void> {
    busy.value = true;
    try {
        await $fetch(`/api/plugins/${encodeURIComponent(pluginId.value)}/setup-values`, {
            method: 'POST',
            // The host mutation guard requires an explicit intent header.
            headers: { 'x-or3-plugin-intent': 'plugin' },
            body: { values },
        });
        message.value = 'Settings saved.';
        await refresh();
    } catch {
        message.value = 'Settings could not be saved.';
    } finally {
        busy.value = false;
    }
}

/** The test URL is derived from the signed package destinations, not user input. */
function connectionUrl(connectionId: string): string {
    const destination =
        data.value?.destinations.find((entry) => entry.id === connectionId) ??
        data.value?.destinations[0];
    const host = destination?.hosts[0] ?? '';
    return `https://${host}/`;
}

async function testConnection(connection: {
    id: string;
    connectionRef?: string;
}): Promise<void> {
    const action = data.value?.plan?.testAction;
    if (!connection.connectionRef || !action) return;
    busy.value = true;
    try {
        const result = await $fetch<{ status?: string; code?: string }>(
            '/api/plugins/connections/test',
            {
                method: 'POST',
                headers: { 'x-or3-plugin-intent': 'plugin' },
                body: {
                    ref: connection.connectionRef,
                    pluginId: pluginId.value,
                    operationId: action.operationId,
                    url: connectionUrl(connection.id),
                },
            }
        );
        message.value =
            result.status === 'ok'
                ? 'Connection works.'
                : `Connection test failed (${result.code ?? 'unknown'}).`;
        await refresh();
    } catch {
        message.value = 'Connection test could not run.';
    } finally {
        busy.value = false;
    }
}

async function runFirstAction(): Promise<void> {
    busy.value = true;
    try {
        const result = await $fetch<{
            status: string;
            handoff?: { label: string; contextKind: string };
            handle?: { handleId: string };
        }>(`/api/plugins/${encodeURIComponent(pluginId.value)}/first-action`, {
            method: 'POST',
            headers: { 'x-or3-plugin-intent': 'plugin' },
            body: {},
        });
        message.value =
            result.status === 'ready'
                ? `${result.handoff?.label ?? 'First action'} is ready on the ${
                      result.handoff?.contextKind === 'sample' ? 'package sample' : 'selection'
                  }.`
                : 'Finish setup before running the first action.';
    } catch {
        message.value = 'The first action could not be started.';
    } finally {
        busy.value = false;
    }
}
</script>

<template>
    <div class="mx-auto flex max-w-3xl flex-col gap-4 p-4">
        <div>
            <h1 class="text-xl font-semibold">{{ pluginId }}</h1>
            <p class="text-sm opacity-70">
                Setup is generated by OR3 from what the plugin declares.
            </p>
        </div>

        <div
            v-if="error"
            class="rounded border border-[var(--md-outline-variant)] p-3 text-sm"
            role="alert"
        >
            This plugin's setup information is unavailable.
        </div>

        <PluginSetupPanel
            v-else-if="data?.plan"
            :plugin-id="pluginId"
            :plan="data.plan"
            :status="data.status"
            :first-action="data.firstAction"
            :durable-connections="data.durableConnections"
            @save-settings="saveSettings"
            @test-connection="testConnection"
            @run-first-action="runFirstAction"
        />

        <p v-else class="text-sm">
            No setup is available for this plugin on this deployment.
        </p>

        <ul v-if="data?.problems?.length" class="text-xs opacity-70">
            <li v-for="problem in data.problems" :key="problem">{{ problem }}</li>
        </ul>

        <p v-if="busy" class="text-xs opacity-70" role="status">Working…</p>
        <p v-if="message" class="text-xs" role="status">{{ message }}</p>
    </div>
</template>
