import type { IconMap } from '~/theme/_shared/icon-registry';

export default <IconMap>{
    // Shell & Navigation
    'shell.sidebar.toggle.left': 'tabler:arrow-bar-to-left',
    'shell.sidebar.toggle.right': 'tabler:arrow-bar-to-right',
    'shell.pane.add': 'tabler:square-plus-2',
    'shell.pane.close': 'tabler:x',
    'shell.theme.light': 'tabler:sun',
    'shell.theme.dark': 'tabler:moon',
    'shell.menu': 'tabler:dots-vertical',
    'shell.back': 'tabler:arrow-left',
    'shell.expand': 'tabler:folder-open',
    'shell.collapse': 'tabler:folder',
    'shell.tab.new': 'tabler:plus',
    'shell.tabs': 'tabler:copy',
    'shell.tabs.search': 'tabler:search',

    // Chat Interface
    'chat.send': 'tabler:arrow-up',
    'chat.stop': 'tabler:square-filled',
    'chat.attach': 'tabler:paperclip',
    'chat.upload': 'tabler:cloud-upload',
    'chat.clear': 'tabler:x',
    'chat.model.search': 'tabler:search',
    'chat.model.settings': 'tabler:adjustments',
    'chat.model.catalog': 'tabler:robot-face',
    'chat.system_prompt': 'tabler:script',
    'chat.web_search': 'tabler:world',
    'chat.message.continue': 'tabler:message-circle-up',

    // Chat Messages
    'chat.message.copy': 'tabler:copy',
    'chat.message.retry': 'tabler:repeat',
    'chat.message.edit': 'tabler:pencil',
    'chat.message.branch': 'tabler:git-branch',
    'chat.message.delete': 'tabler:trash',
    'chat.reasoning': 'tabler:bulb',

    // Tool Indicators
    'chat.tool.loader': 'tabler:loader-2',
    'chat.tool.check': 'tabler:check',
    'chat.tool.error': 'tabler:x',
    'chat.tool.wrench': 'tabler:tool',

    // Sidebar
    'sidebar.search': 'tabler:search',
    'sidebar.new_chat': 'tabler:message-circle-plus',
    'sidebar.new_folder': 'tabler:folder-plus',
    'sidebar.new_note': 'tabler:file-plus',
    'sidebar.edit': 'tabler:pencil',
    'sidebar.delete': 'tabler:trash',
    'sidebar.folder': 'tabler:folder',
    'sidebar.chat': 'tabler:message-circle',
    'sidebar.note': 'tabler:file-description',
    'sidebar.settings': 'tabler:adjustments',
    'sidebar.user': 'tabler:user',
    'sidebar.activity': 'tabler:activity-heartbeat',
    'sidebar.credits': 'tabler:coins',
    'sidebar.project.root': 'tabler:home',
    'sidebar.page.home': 'tabler:home',
    'sidebar.page.messages': 'tabler:messages',
    'sidebar.page.default': 'tabler:layout-grid',

    // Common UI
    'ui.check': 'tabler:check',
    'ui.close': 'tabler:x',
    'ui.copy': 'tabler:copy',
    'ui.trash': 'tabler:trash',
    'ui.edit': 'tabler:pencil',
    'ui.warning': 'tabler:alert-square-rounded',
    'ui.info': 'tabler:info-square-rounded',
    'ui.loading': 'tabler:loader',
    'ui.more': 'tabler:dots-vertical',
    'ui.download': 'tabler:download',
    'ui.upload': 'tabler:cloud-upload',
    'ui.search': 'tabler:search',
    'ui.filter': 'tabler:filter-2',
    'ui.sort': 'tabler:arrows-sort',
    'ui.view': 'tabler:eye',
    'ui.view_off': 'tabler:eye-closed',
    'ui.lock': 'tabler:lock',
    'ui.unlock': 'tabler:lock-open',
    'ui.settings': 'tabler:adjustments',
    'ui.unknown': 'tabler:alert-square-rounded',
    'ui.clock': 'tabler:clock',
    'ui.chart': 'tabler:chart-bar',
    'ui.shield': 'tabler:shield',
    'ui.cloud': 'tabler:cloud',
    'ui.chevron.right': 'tabler:chevron-right',
    'ui.chevron.left': 'tabler:chevron-left',
    'ui.chevron.down': 'tabler:chevron-down',
    'ui.wait': 'tabler:hourglass',
    'ui.minus': 'tabler:minus',
    'ui.plus': 'tabler:plus',
    'ui.help': 'tabler:message-question',
    'ui.star': 'tabler:star',
    'ui.moon': 'tabler:moon',
    'ui.dino': 'tabler:bug',
    'ui.refresh': 'tabler:reload',
    'ui.fullscreen': 'material-symbols:fullscreen',
    'ui.fullscreen.exit': 'material-symbols:fullscreen-exit',
    'ui.menu': 'tabler:menu-2',
    'ui.notes': 'tabler:notes',
    'ui.notes.multiple': 'tabler:notebook',
    'ui.chat': 'tabler:message',
    'ui.sync': 'tabler:refresh',
    'ui.checkbox.on': 'tabler:checkbox',
    'ui.checkbox.off': 'tabler:square',
    'ui.book': 'tabler:book',
    'ui.hint': 'tabler:info-circle',
    'ui.calendar': 'tabler:calendar',
    'ui.sparkles': 'tabler:sparkles',
    'ui.drag': 'tabler:grip-vertical',
    'ui.flame': 'tabler:flame',
    'ui.leaf': 'tabler:leaf',
    'ui.list.todo': 'tabler:list-check',
    'ui.list.checks': 'tabler:list',

    // Dashboard
    'dashboard.home': 'tabler:layout-dashboard',
    'dashboard.plugins': 'tabler:plug',
    'dashboard.settings': 'tabler:adjustments-horizontal',
    'dashboard.images': 'tabler:photo',
    'dashboard.backup': 'tabler:book-upload',
    'dashboard.restore': 'tabler:book-upload',

    // Admin
    'admin.workspace': 'tabler:building',
    'admin.workspaces': 'tabler:buildings',

    // Documents / Editor
    'editor.document': 'tabler:file-description',
    'editor.search': 'tabler:search',
    'editor.inspector': 'tabler:layout-sidebar-right',
    'editor.more': 'tabler:dots',
    'editor.close': 'tabler:x',
    'editor.previous': 'tabler:chevron-up',
    'editor.next': 'tabler:chevron-down',
    'editor.ai': 'tabler:sparkles',
    'editor.outline': 'tabler:list-tree',
    'editor.history': 'tabler:history',
    'editor.info': 'tabler:info-circle',
    'editor.plugin': 'tabler:plug',
    'editor.settings': 'tabler:adjustments',
    'editor.send': 'tabler:arrow-up',
    'editor.stop': 'tabler:square-filled',
    'editor.format.bold': 'tabler:bold',
    'editor.format.italic': 'tabler:italic',
    'editor.format.underline': 'tabler:underline',
    'editor.format.strike': 'tabler:strikethrough',
    'editor.format.link': 'tabler:link',
    'editor.format.quote': 'tabler:blockquote',
    'editor.format.bullet-list': 'tabler:list',
    'editor.format.ordered-list': 'tabler:list-numbers',
    'editor.format.task-list': 'tabler:list-check',
    'editor.insert.text': 'tabler:letter-t',
    'editor.insert.heading-1': 'tabler:h-1',
    'editor.insert.heading-2': 'tabler:h-2',
    'editor.insert.code-block': 'tabler:code',
    'editor.insert.divider': 'tabler:minus',
    'editor.insert.table': 'tabler:table',
    'editor.insert.image': 'tabler:photo-plus',
    'editor.code': 'tabler:code',
    'editor.list': 'tabler:list',
    'editor.undo': 'tabler:arrow-back-up',
    'editor.redo': 'tabler:arrow-forward-up',

    // Images
    'image.download': 'tabler:download',
    'image.copy': 'tabler:copy',
    'image.delete': 'tabler:photo-x',
    'image.repeat': 'tabler:repeat',
    'image.multiple': 'tabler:library-photo',

    'notification.bell': 'tabler:bell',
    'notification.message': 'tabler:message',
    'notification.warning': 'tabler:alert-triangle',
    'notification.sync': 'tabler:refresh',

    // External Agents
    'external-agent.bot': 'tabler:robot',
    'external-agent.connect': 'tabler:plug-connected',
    'external-agent.disconnect': 'tabler:plug-x',
    'external-agent.key': 'tabler:key',
    'external-agent.install': 'tabler:device-desktop-up',
    'external-agent.package': 'tabler:package',
    'external-agent.server': 'tabler:server-cog',
    'external-agent.server.off': 'tabler:server-off',
    'external-agent.network': 'tabler:network',
    'external-agent.tag': 'tabler:tag',
    'external-agent.link': 'tabler:link',
    'external-agent.link.off': 'tabler:unlink',
    'external-agent.search.empty': 'tabler:search-off',
    'external-agent.file': 'tabler:file',
    'external-agent.file.text': 'tabler:file-text',
    'external-agent.file.audio': 'tabler:file-music',
    'external-agent.file.video': 'tabler:movie',
    'external-agent.file.pdf': 'tabler:file-type-pdf',
    'external-agent.file.diff': 'tabler:file-diff',
    'external-agent.drop': 'tabler:file-upload',
    'external-agent.shield.alert': 'tabler:shield-exclamation',
    'external-agent.shield.check': 'tabler:shield-check',
};
