import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { relative, resolve } from 'node:path';
import ts from 'typescript';

const repoRoot = resolve(import.meta.dir, '..');
const providers = [
    'or3-provider-clerk',
    'or3-provider-convex',
    'or3-provider-fs',
    'or3-provider-s3',
    'or3-provider-sqlite',
] as const;

const typeOverrides: Readonly<Record<string, Readonly<Record<string, string>>>> = {
    'or3-provider-convex': {
        PendingOp:
            'export type PendingOp = { stamp: { opId: string; [key: string]: any }; tableName: string; operation: string; payload?: any; [key: string]: any };',
        PushBatch:
            'export type PushBatch = { scope: any; ops: PendingOp[]; [key: string]: any };',
        PushResult:
            'export type PushResult = { results: Array<Record<string, any>>; [key: string]: any };',
    },
};

function sourceFiles(directory: string): string[] {
    return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
        const path = resolve(directory, entry.name);
        if (entry.isDirectory()) {
            return entry.name === '__tests__' || entry.name === 'shims'
                ? []
                : sourceFiles(path);
        }
        return entry.isFile() && path.endsWith('.ts') ? [path] : [];
    });
}

function isHostContractImport(specifier: string): boolean {
    return (
        specifier === '#app' ||
        specifier === '~~' ||
        specifier === '~' ||
        specifier.startsWith('~~/') ||
        specifier.startsWith('~/')
    );
}

function importedHostSymbols(providerRoot: string): string[] {
    const symbols = new Set<string>();
    for (const path of sourceFiles(resolve(providerRoot, 'src'))) {
        const source = ts.createSourceFile(
            path,
            readFileSync(path, 'utf8'),
            ts.ScriptTarget.Latest,
            true,
        );
        for (const statement of source.statements) {
            if (!ts.isImportDeclaration(statement)) continue;
            if (!ts.isStringLiteral(statement.moduleSpecifier)) continue;
            if (!isHostContractImport(statement.moduleSpecifier.text)) continue;
            const bindings = statement.importClause?.namedBindings;
            if (!bindings || !ts.isNamedImports(bindings)) continue;
            for (const item of bindings.elements) {
                symbols.add((item.propertyName ?? item.name).text);
            }
        }
    }
    return [...symbols].sort((a, b) => a.localeCompare(b));
}

export function generateProviderHostContract(providerRoot: string): string {
    const symbols = importedHostSymbols(providerRoot);
    const provider = providerRoot.split('/').at(-1) ?? '';
    const overrides = typeOverrides[provider] ?? {};
    return [
        '// Generated by scripts/generate-provider-host-contracts.ts.',
        '// This release-only shim is derived from host imports; do not edit by hand.',
        '',
        ...symbols.flatMap((symbol) => [
            overrides[symbol] ??
                `export type ${symbol}<T = any, U = any, V = any, W = any, X = any> = any;`,
            `export const ${symbol}: any = undefined;`,
        ]),
        '',
    ].join('\n');
}

export function writeOrCheckProviderHostContracts(checkOnly: boolean): void {
    for (const provider of providers) {
        const providerRoot = resolve(repoRoot, '..', provider);
        const target = resolve(providerRoot, 'src/shims/or3-chat-contract.ts');
        const content = generateProviderHostContract(providerRoot);
        if (checkOnly) {
            if (!existsSync(target) || readFileSync(target, 'utf8') !== content) {
                throw new Error(
                    `[provider-host-contracts] ${relative(repoRoot, target)} is stale; run bun run provider-host-contracts`,
                );
            }
            continue;
        }
        writeFileSync(target, content);
    }
}

if (import.meta.main) {
    const checkOnly = process.argv.includes('--check');
    writeOrCheckProviderHostContracts(checkOnly);
    console.log(`[provider-host-contracts] ${checkOnly ? 'verified' : 'wrote'} generated host contract fixtures`);
}
