import { writeFile, rename, rm } from 'node:fs/promises';
import { resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import type { WizardAnswers } from './types';

export type InitialCredentials = {
    bootstrapEmail?: string;
    bootstrapPassword?: string;
    adminUsername?: string;
    adminPassword?: string;
};

export function serializeInitialCredentials(
    credentials: InitialCredentials
): string | null {
    const lines = ['# OR3 first-run credentials — move to a password manager, then delete this file.'];
    if (credentials.bootstrapEmail) {
        lines.push(
            `OR3_BASIC_AUTH_BOOTSTRAP_EMAIL=${serializeCredentialValue(credentials.bootstrapEmail)}`
        );
    }
    if (credentials.bootstrapPassword) {
        lines.push(
            `OR3_BASIC_AUTH_BOOTSTRAP_PASSWORD=${serializeCredentialValue(credentials.bootstrapPassword)}`
        );
    }
    if (credentials.adminUsername) {
        lines.push(`OR3_ADMIN_USERNAME=${serializeCredentialValue(credentials.adminUsername)}`);
    }
    if (credentials.adminPassword) {
        lines.push(`OR3_ADMIN_PASSWORD=${serializeCredentialValue(credentials.adminPassword)}`);
    }
    return lines.length === 1 ? null : `${lines.join('\n')}\n`;
}

function serializeCredentialValue(value: string): string {
    if (value.includes('\0') || /\r|\n/.test(value)) {
        throw new Error('Credential values may not contain NUL or newline characters.');
    }
    if (/^[A-Za-z0-9._:@%+=/-]+$/.test(value)) return value;
    return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;
}

/**
 * Writes generated first-run credentials without exposing them in terminal
 * scrollback or redirected setup logs. Callers must tell the user where the
 * file is; they must never print its contents.
 */
export async function writeInitialCredentialsFile(
    instanceDir: string,
    credentials: InitialCredentials
): Promise<string | null> {
    const content = serializeInitialCredentials(credentials);
    if (!content) return null;

    const path = resolve(instanceDir, '.or3-initial-credentials');
    const temporary = `${path}.${randomUUID()}.tmp`;
    try {
        await writeFile(temporary, content, { mode: 0o600 });
        await rename(temporary, path);
    } finally {
        await rm(temporary, { force: true });
    }
    return path;
}

/** Uses the final applied answers, including secrets generated by preset defaults. */
export function initialLoginCredentials(answers: WizardAnswers): InitialCredentials {
    const basicAuth = answers.ssrAuthEnabled && answers.authProvider === 'basic-auth';
    return {
        bootstrapEmail: basicAuth ? answers.basicAuthBootstrapEmail : undefined,
        bootstrapPassword: basicAuth ? answers.basicAuthBootstrapPassword : undefined,
        adminUsername: answers.ssrAuthEnabled ? answers.adminUsername : undefined,
        adminPassword: answers.ssrAuthEnabled ? answers.adminPassword : undefined,
    };
}
